
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance_12)
    (:domain Sokoban)

    (:objects
        
    )

    (:init
        (clear-loc_0_0 )
        (clear-loc_0_1 )
        (clear-loc_0_2 )
        (clear-loc_0_3 )
        (clear-loc_0_7 )
        (clear-loc_0_8 )
        (clear-loc_1_5 )
        (clear-loc_1_7 )
        (clear-loc_1_8 )
        (clear-loc_2_1 )
        (clear-loc_2_2 )
        (clear-loc_2_3 )
        (clear-loc_2_5 )
        (clear-loc_3_1 )
        (clear-loc_3_2 )
        (clear-loc_3_3 )
        (box-loc_3_4 )
        (clear-loc_3_5 )
        (clear-loc_3_6 )
        (clear-loc_3_7 )
        (clear-loc_4_5 )
        (clear-loc_5_0 )
        (clear-loc_5_1 )
        (clear-loc_5_2 )
        (clear-loc_5_3 )
        (at-loc_5_5 )
        (clear-loc_5_7 )
        (clear-loc_5_8 )
        (clear-loc_6_0 )
        (clear-loc_6_1 )
        (clear-loc_6_2 )
        (clear-loc_6_3 )
        (clear-loc_6_7 )
        (clear-loc_6_8 )
    )

    (:goal
        (box-loc_3_7 )
    )

    
    
    
)

