
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain Sokoban)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (at-loc_0_0 )
        (box-loc_0_0 )
        (clear-loc_0_0 )
        (at-loc_0_1 )
        (box-loc_0_1 )
        (clear-loc_0_1 )
        (at-loc_0_2 )
        (box-loc_0_2 )
        (clear-loc_0_2 )
        (at-loc_0_3 )
        (box-loc_0_3 )
        (clear-loc_0_3 )
        (at-loc_0_4 )
        (box-loc_0_4 )
        (clear-loc_0_4 )
        (at-loc_0_5 )
        (box-loc_0_5 )
        (clear-loc_0_5 )
        (at-loc_0_6 )
        (box-loc_0_6 )
        (clear-loc_0_6 )
        (at-loc_0_7 )
        (box-loc_0_7 )
        (clear-loc_0_7 )
        (at-loc_0_8 )
        (box-loc_0_8 )
        (clear-loc_0_8 )
        (at-loc_0_12 )
        (box-loc_0_12 )
        (clear-loc_0_12 )
        (at-loc_0_13 )
        (box-loc_0_13 )
        (clear-loc_0_13 )
        (at-loc_0_14 )
        (box-loc_0_14 )
        (clear-loc_0_14 )
        (at-loc_1_0 )
        (box-loc_1_0 )
        (clear-loc_1_0 )
        (at-loc_1_1 )
        (box-loc_1_1 )
        (clear-loc_1_1 )
        (at-loc_1_10 )
        (box-loc_1_10 )
        (clear-loc_1_10 )
        (at-loc_2_0 )
        (box-loc_2_0 )
        (clear-loc_2_0 )
        (at-loc_2_1 )
        (box-loc_2_1 )
        (clear-loc_2_1 )
        (at-loc_2_3 )
        (box-loc_2_3 )
        (clear-loc_2_3 )
        (at-loc_2_4 )
        (box-loc_2_4 )
        (clear-loc_2_4 )
        (at-loc_2_5 )
        (box-loc_2_5 )
        (clear-loc_2_5 )
        (at-loc_2_6 )
        (box-loc_2_6 )
        (clear-loc_2_6 )
        (at-loc_2_7 )
        (box-loc_2_7 )
        (clear-loc_2_7 )
        (at-loc_2_8 )
        (box-loc_2_8 )
        (clear-loc_2_8 )
        (at-loc_2_9 )
        (box-loc_2_9 )
        (clear-loc_2_9 )
        (at-loc_2_10 )
        (box-loc_2_10 )
        (clear-loc_2_10 )
        (at-loc_2_12 )
        (box-loc_2_12 )
        (clear-loc_2_12 )
        (at-loc_2_13 )
        (box-loc_2_13 )
        (clear-loc_2_13 )
        (at-loc_3_0 )
        (box-loc_3_0 )
        (clear-loc_3_0 )
        (at-loc_3_1 )
        (box-loc_3_1 )
        (clear-loc_3_1 )
        (at-loc_3_3 )
        (box-loc_3_3 )
        (clear-loc_3_3 )
        (at-loc_3_4 )
        (box-loc_3_4 )
        (clear-loc_3_4 )
        (at-loc_3_8 )
        (box-loc_3_8 )
        (clear-loc_3_8 )
        (at-loc_3_9 )
        (box-loc_3_9 )
        (clear-loc_3_9 )
        (at-loc_3_10 )
        (box-loc_3_10 )
        (clear-loc_3_10 )
        (at-loc_3_11 )
        (box-loc_3_11 )
        (clear-loc_3_11 )
        (at-loc_3_12 )
        (box-loc_3_12 )
        (clear-loc_3_12 )
        (at-loc_3_13 )
        (box-loc_3_13 )
        (clear-loc_3_13 )
        (at-loc_4_3 )
        (box-loc_4_3 )
        (clear-loc_4_3 )
        (at-loc_4_4 )
        (box-loc_4_4 )
        (clear-loc_4_4 )
        (at-loc_4_6 )
        (box-loc_4_6 )
        (clear-loc_4_6 )
        (at-loc_4_7 )
        (box-loc_4_7 )
        (clear-loc_4_7 )
        (at-loc_4_9 )
        (box-loc_4_9 )
        (clear-loc_4_9 )
        (at-loc_4_10 )
        (box-loc_4_10 )
        (clear-loc_4_10 )
        (at-loc_4_12 )
        (box-loc_4_12 )
        (clear-loc_4_12 )
        (at-loc_4_13 )
        (box-loc_4_13 )
        (clear-loc_4_13 )
        (at-loc_5_1 )
        (box-loc_5_1 )
        (clear-loc_5_1 )
        (at-loc_5_2 )
        (box-loc_5_2 )
        (clear-loc_5_2 )
        (at-loc_5_3 )
        (box-loc_5_3 )
        (clear-loc_5_3 )
        (at-loc_5_4 )
        (box-loc_5_4 )
        (clear-loc_5_4 )
        (at-loc_5_5 )
        (box-loc_5_5 )
        (clear-loc_5_5 )
        (at-loc_5_6 )
        (box-loc_5_6 )
        (clear-loc_5_6 )
        (at-loc_5_7 )
        (box-loc_5_7 )
        (clear-loc_5_7 )
        (at-loc_5_8 )
        (box-loc_5_8 )
        (clear-loc_5_8 )
        (at-loc_5_9 )
        (box-loc_5_9 )
        (clear-loc_5_9 )
        (at-loc_6_3 )
        (box-loc_6_3 )
        (clear-loc_6_3 )
        (at-loc_6_4 )
        (box-loc_6_4 )
        (clear-loc_6_4 )
        (at-loc_6_5 )
        (box-loc_6_5 )
        (clear-loc_6_5 )
        (at-loc_6_6 )
        (box-loc_6_6 )
        (clear-loc_6_6 )
        (at-loc_6_8 )
        (box-loc_6_8 )
        (clear-loc_6_8 )
        (at-loc_6_9 )
        (box-loc_6_9 )
        (clear-loc_6_9 )
        (at-loc_6_11 )
        (box-loc_6_11 )
        (clear-loc_6_11 )
        (at-loc_6_12 )
        (box-loc_6_12 )
        (clear-loc_6_12 )
        (at-loc_6_13 )
        (box-loc_6_13 )
        (clear-loc_6_13 )
        (at-loc_6_14 )
        (box-loc_6_14 )
        (clear-loc_6_14 )
        (at-loc_7_0 )
        (box-loc_7_0 )
        (clear-loc_7_0 )
        (at-loc_7_1 )
        (box-loc_7_1 )
        (clear-loc_7_1 )
        (at-loc_7_11 )
        (box-loc_7_11 )
        (clear-loc_7_11 )
        (at-loc_7_12 )
        (box-loc_7_12 )
        (clear-loc_7_12 )
        (at-loc_7_13 )
        (box-loc_7_13 )
        (clear-loc_7_13 )
        (at-loc_7_14 )
        (box-loc_7_14 )
        (clear-loc_7_14 )
    )

    (:functions
        
    )

    

    
    (:action move-loc_0_0-loc_1_0
     :parameters ()
     :precondition (and (clear-loc_1_0 ) (at-loc_0_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (clear-loc_1_0 ))
        (at-loc_1_0 )
        (clear-loc_0_0 ))
    )


    (:action move-loc_1_0-loc_0_0
     :parameters ()
     :precondition (and (clear-loc_0_0 ) (at-loc_1_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_0 )
        (clear-loc_1_0 ))
    )


    (:action move-loc_0_1-loc_1_1
     :parameters ()
     :precondition (and (clear-loc_1_1 ) (at-loc_0_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (clear-loc_1_1 ))
        (at-loc_1_1 )
        (clear-loc_0_1 ))
    )


    (:action move-loc_1_1-loc_0_1
     :parameters ()
     :precondition (and (clear-loc_0_1 ) (at-loc_1_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_1 )
        (clear-loc_1_1 ))
    )


    (:action move-loc_1_0-loc_2_0
     :parameters ()
     :precondition (and (clear-loc_2_0 ) (at-loc_1_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (clear-loc_2_0 ))
        (at-loc_2_0 )
        (clear-loc_1_0 ))
    )


    (:action move-loc_2_0-loc_1_0
     :parameters ()
     :precondition (and (clear-loc_1_0 ) (at-loc_2_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (clear-loc_1_0 ))
        (at-loc_1_0 )
        (clear-loc_2_0 ))
    )


    (:action move-loc_1_1-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_1_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_1_1 ))
    )


    (:action move-loc_2_1-loc_1_1
     :parameters ()
     :precondition (and (clear-loc_1_1 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_1_1 ))
        (at-loc_1_1 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_1_10-loc_2_10
     :parameters ()
     :precondition (and (clear-loc_2_10 ) (at-loc_1_10 ))
     :effect (and
        (not (at-loc_1_10 ))
        (not (clear-loc_2_10 ))
        (at-loc_2_10 )
        (clear-loc_1_10 ))
    )


    (:action move-loc_2_10-loc_1_10
     :parameters ()
     :precondition (and (clear-loc_1_10 ) (at-loc_2_10 ))
     :effect (and
        (not (at-loc_2_10 ))
        (not (clear-loc_1_10 ))
        (at-loc_1_10 )
        (clear-loc_2_10 ))
    )


    (:action move-loc_2_0-loc_3_0
     :parameters ()
     :precondition (and (clear-loc_3_0 ) (at-loc_2_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (clear-loc_3_0 ))
        (at-loc_3_0 )
        (clear-loc_2_0 ))
    )


    (:action move-loc_3_0-loc_2_0
     :parameters ()
     :precondition (and (clear-loc_2_0 ) (at-loc_3_0 ))
     :effect (and
        (not (at-loc_3_0 ))
        (not (clear-loc_2_0 ))
        (at-loc_2_0 )
        (clear-loc_3_0 ))
    )


    (:action move-loc_2_1-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_3_1-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_2_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_3_3-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_3_4-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_2_8-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_3_8-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_2_9-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_3_9-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_2_10-loc_3_10
     :parameters ()
     :precondition (and (clear-loc_3_10 ) (at-loc_2_10 ))
     :effect (and
        (not (at-loc_2_10 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_10 )
        (clear-loc_2_10 ))
    )


    (:action move-loc_3_10-loc_2_10
     :parameters ()
     :precondition (and (clear-loc_2_10 ) (at-loc_3_10 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (clear-loc_2_10 ))
        (at-loc_2_10 )
        (clear-loc_3_10 ))
    )


    (:action move-loc_2_12-loc_3_12
     :parameters ()
     :precondition (and (clear-loc_3_12 ) (at-loc_2_12 ))
     :effect (and
        (not (at-loc_2_12 ))
        (not (clear-loc_3_12 ))
        (at-loc_3_12 )
        (clear-loc_2_12 ))
    )


    (:action move-loc_3_12-loc_2_12
     :parameters ()
     :precondition (and (clear-loc_2_12 ) (at-loc_3_12 ))
     :effect (and
        (not (at-loc_3_12 ))
        (not (clear-loc_2_12 ))
        (at-loc_2_12 )
        (clear-loc_3_12 ))
    )


    (:action move-loc_2_13-loc_3_13
     :parameters ()
     :precondition (and (clear-loc_3_13 ) (at-loc_2_13 ))
     :effect (and
        (not (at-loc_2_13 ))
        (not (clear-loc_3_13 ))
        (at-loc_3_13 )
        (clear-loc_2_13 ))
    )


    (:action move-loc_3_13-loc_2_13
     :parameters ()
     :precondition (and (clear-loc_2_13 ) (at-loc_3_13 ))
     :effect (and
        (not (at-loc_3_13 ))
        (not (clear-loc_2_13 ))
        (at-loc_2_13 )
        (clear-loc_3_13 ))
    )


    (:action move-loc_3_3-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_4_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_3_4-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_3_9-loc_4_9
     :parameters ()
     :precondition (and (clear-loc_4_9 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_4_9 ))
        (at-loc_4_9 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_4_9-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_4_9 ))
     :effect (and
        (not (at-loc_4_9 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_4_9 ))
    )


    (:action move-loc_3_10-loc_4_10
     :parameters ()
     :precondition (and (clear-loc_4_10 ) (at-loc_3_10 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (clear-loc_4_10 ))
        (at-loc_4_10 )
        (clear-loc_3_10 ))
    )


    (:action move-loc_4_10-loc_3_10
     :parameters ()
     :precondition (and (clear-loc_3_10 ) (at-loc_4_10 ))
     :effect (and
        (not (at-loc_4_10 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_10 )
        (clear-loc_4_10 ))
    )


    (:action move-loc_3_12-loc_4_12
     :parameters ()
     :precondition (and (clear-loc_4_12 ) (at-loc_3_12 ))
     :effect (and
        (not (at-loc_3_12 ))
        (not (clear-loc_4_12 ))
        (at-loc_4_12 )
        (clear-loc_3_12 ))
    )


    (:action move-loc_4_12-loc_3_12
     :parameters ()
     :precondition (and (clear-loc_3_12 ) (at-loc_4_12 ))
     :effect (and
        (not (at-loc_4_12 ))
        (not (clear-loc_3_12 ))
        (at-loc_3_12 )
        (clear-loc_4_12 ))
    )


    (:action move-loc_3_13-loc_4_13
     :parameters ()
     :precondition (and (clear-loc_4_13 ) (at-loc_3_13 ))
     :effect (and
        (not (at-loc_3_13 ))
        (not (clear-loc_4_13 ))
        (at-loc_4_13 )
        (clear-loc_3_13 ))
    )


    (:action move-loc_4_13-loc_3_13
     :parameters ()
     :precondition (and (clear-loc_3_13 ) (at-loc_4_13 ))
     :effect (and
        (not (at-loc_4_13 ))
        (not (clear-loc_3_13 ))
        (at-loc_3_13 )
        (clear-loc_4_13 ))
    )


    (:action move-loc_4_3-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_5_3-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_4_4-loc_5_4
     :parameters ()
     :precondition (and (clear-loc_5_4 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_4 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_5_4-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_5_4 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_5_4 ))
    )


    (:action move-loc_4_6-loc_5_6
     :parameters ()
     :precondition (and (clear-loc_5_6 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_6 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_5_6-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_5_6 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_5_6 ))
    )


    (:action move-loc_4_7-loc_5_7
     :parameters ()
     :precondition (and (clear-loc_5_7 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_7 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_5_7-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_5_7 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_5_7 ))
    )


    (:action move-loc_4_9-loc_5_9
     :parameters ()
     :precondition (and (clear-loc_5_9 ) (at-loc_4_9 ))
     :effect (and
        (not (at-loc_4_9 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_9 )
        (clear-loc_4_9 ))
    )


    (:action move-loc_5_9-loc_4_9
     :parameters ()
     :precondition (and (clear-loc_4_9 ) (at-loc_5_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (clear-loc_4_9 ))
        (at-loc_4_9 )
        (clear-loc_5_9 ))
    )


    (:action move-loc_5_3-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_6_3-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_5_4-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_5_4 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_5_4 ))
    )


    (:action move-loc_6_4-loc_5_4
     :parameters ()
     :precondition (and (clear-loc_5_4 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_4 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_5_5-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_6_5-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_5_6-loc_6_6
     :parameters ()
     :precondition (and (clear-loc_6_6 ) (at-loc_5_6 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_6 )
        (clear-loc_5_6 ))
    )


    (:action move-loc_6_6-loc_5_6
     :parameters ()
     :precondition (and (clear-loc_5_6 ) (at-loc_6_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_6 )
        (clear-loc_6_6 ))
    )


    (:action move-loc_5_8-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_6_8-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_5_9-loc_6_9
     :parameters ()
     :precondition (and (clear-loc_6_9 ) (at-loc_5_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_9 )
        (clear-loc_5_9 ))
    )


    (:action move-loc_6_9-loc_5_9
     :parameters ()
     :precondition (and (clear-loc_5_9 ) (at-loc_6_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_9 )
        (clear-loc_6_9 ))
    )


    (:action move-loc_6_11-loc_7_11
     :parameters ()
     :precondition (and (clear-loc_7_11 ) (at-loc_6_11 ))
     :effect (and
        (not (at-loc_6_11 ))
        (not (clear-loc_7_11 ))
        (at-loc_7_11 )
        (clear-loc_6_11 ))
    )


    (:action move-loc_7_11-loc_6_11
     :parameters ()
     :precondition (and (clear-loc_6_11 ) (at-loc_7_11 ))
     :effect (and
        (not (at-loc_7_11 ))
        (not (clear-loc_6_11 ))
        (at-loc_6_11 )
        (clear-loc_7_11 ))
    )


    (:action move-loc_6_12-loc_7_12
     :parameters ()
     :precondition (and (clear-loc_7_12 ) (at-loc_6_12 ))
     :effect (and
        (not (at-loc_6_12 ))
        (not (clear-loc_7_12 ))
        (at-loc_7_12 )
        (clear-loc_6_12 ))
    )


    (:action move-loc_7_12-loc_6_12
     :parameters ()
     :precondition (and (clear-loc_6_12 ) (at-loc_7_12 ))
     :effect (and
        (not (at-loc_7_12 ))
        (not (clear-loc_6_12 ))
        (at-loc_6_12 )
        (clear-loc_7_12 ))
    )


    (:action move-loc_6_13-loc_7_13
     :parameters ()
     :precondition (and (clear-loc_7_13 ) (at-loc_6_13 ))
     :effect (and
        (not (at-loc_6_13 ))
        (not (clear-loc_7_13 ))
        (at-loc_7_13 )
        (clear-loc_6_13 ))
    )


    (:action move-loc_7_13-loc_6_13
     :parameters ()
     :precondition (and (clear-loc_6_13 ) (at-loc_7_13 ))
     :effect (and
        (not (at-loc_7_13 ))
        (not (clear-loc_6_13 ))
        (at-loc_6_13 )
        (clear-loc_7_13 ))
    )


    (:action move-loc_6_14-loc_7_14
     :parameters ()
     :precondition (and (clear-loc_7_14 ) (at-loc_6_14 ))
     :effect (and
        (not (at-loc_6_14 ))
        (not (clear-loc_7_14 ))
        (at-loc_7_14 )
        (clear-loc_6_14 ))
    )


    (:action move-loc_7_14-loc_6_14
     :parameters ()
     :precondition (and (clear-loc_6_14 ) (at-loc_7_14 ))
     :effect (and
        (not (at-loc_7_14 ))
        (not (clear-loc_6_14 ))
        (at-loc_6_14 )
        (clear-loc_7_14 ))
    )


    (:action move-loc_0_0-loc_0_1
     :parameters ()
     :precondition (and (clear-loc_0_1 ) (at-loc_0_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_1 )
        (clear-loc_0_0 ))
    )


    (:action move-loc_0_1-loc_0_0
     :parameters ()
     :precondition (and (clear-loc_0_0 ) (at-loc_0_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_0 )
        (clear-loc_0_1 ))
    )


    (:action move-loc_0_1-loc_0_2
     :parameters ()
     :precondition (and (clear-loc_0_2 ) (at-loc_0_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_2 )
        (clear-loc_0_1 ))
    )


    (:action move-loc_0_2-loc_0_1
     :parameters ()
     :precondition (and (clear-loc_0_1 ) (at-loc_0_2 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_1 )
        (clear-loc_0_2 ))
    )


    (:action move-loc_0_2-loc_0_3
     :parameters ()
     :precondition (and (clear-loc_0_3 ) (at-loc_0_2 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_3 )
        (clear-loc_0_2 ))
    )


    (:action move-loc_0_3-loc_0_2
     :parameters ()
     :precondition (and (clear-loc_0_2 ) (at-loc_0_3 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_2 )
        (clear-loc_0_3 ))
    )


    (:action move-loc_0_3-loc_0_4
     :parameters ()
     :precondition (and (clear-loc_0_4 ) (at-loc_0_3 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_4 )
        (clear-loc_0_3 ))
    )


    (:action move-loc_0_4-loc_0_3
     :parameters ()
     :precondition (and (clear-loc_0_3 ) (at-loc_0_4 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_3 )
        (clear-loc_0_4 ))
    )


    (:action move-loc_0_4-loc_0_5
     :parameters ()
     :precondition (and (clear-loc_0_5 ) (at-loc_0_4 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_5 )
        (clear-loc_0_4 ))
    )


    (:action move-loc_0_5-loc_0_4
     :parameters ()
     :precondition (and (clear-loc_0_4 ) (at-loc_0_5 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_4 )
        (clear-loc_0_5 ))
    )


    (:action move-loc_0_5-loc_0_6
     :parameters ()
     :precondition (and (clear-loc_0_6 ) (at-loc_0_5 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_6 )
        (clear-loc_0_5 ))
    )


    (:action move-loc_0_6-loc_0_5
     :parameters ()
     :precondition (and (clear-loc_0_5 ) (at-loc_0_6 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_5 )
        (clear-loc_0_6 ))
    )


    (:action move-loc_0_6-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_0_6 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_0_6 ))
    )


    (:action move-loc_0_7-loc_0_6
     :parameters ()
     :precondition (and (clear-loc_0_6 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_6 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_0_7-loc_0_8
     :parameters ()
     :precondition (and (clear-loc_0_8 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_8 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_0_8-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_0_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_0_8 ))
    )


    (:action move-loc_0_12-loc_0_13
     :parameters ()
     :precondition (and (clear-loc_0_13 ) (at-loc_0_12 ))
     :effect (and
        (not (at-loc_0_12 ))
        (not (clear-loc_0_13 ))
        (at-loc_0_13 )
        (clear-loc_0_12 ))
    )


    (:action move-loc_0_13-loc_0_12
     :parameters ()
     :precondition (and (clear-loc_0_12 ) (at-loc_0_13 ))
     :effect (and
        (not (at-loc_0_13 ))
        (not (clear-loc_0_12 ))
        (at-loc_0_12 )
        (clear-loc_0_13 ))
    )


    (:action move-loc_0_13-loc_0_14
     :parameters ()
     :precondition (and (clear-loc_0_14 ) (at-loc_0_13 ))
     :effect (and
        (not (at-loc_0_13 ))
        (not (clear-loc_0_14 ))
        (at-loc_0_14 )
        (clear-loc_0_13 ))
    )


    (:action move-loc_0_14-loc_0_13
     :parameters ()
     :precondition (and (clear-loc_0_13 ) (at-loc_0_14 ))
     :effect (and
        (not (at-loc_0_14 ))
        (not (clear-loc_0_13 ))
        (at-loc_0_13 )
        (clear-loc_0_14 ))
    )


    (:action move-loc_1_0-loc_1_1
     :parameters ()
     :precondition (and (clear-loc_1_1 ) (at-loc_1_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (clear-loc_1_1 ))
        (at-loc_1_1 )
        (clear-loc_1_0 ))
    )


    (:action move-loc_1_1-loc_1_0
     :parameters ()
     :precondition (and (clear-loc_1_0 ) (at-loc_1_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (clear-loc_1_0 ))
        (at-loc_1_0 )
        (clear-loc_1_1 ))
    )


    (:action move-loc_2_0-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_2_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_2_0 ))
    )


    (:action move-loc_2_1-loc_2_0
     :parameters ()
     :precondition (and (clear-loc_2_0 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_2_0 ))
        (at-loc_2_0 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_2_3-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_2_4-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_2_4-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_2_5-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_2_5-loc_2_6
     :parameters ()
     :precondition (and (clear-loc_2_6 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_6 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_2_6-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_2_6 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_2_6 ))
    )


    (:action move-loc_2_6-loc_2_7
     :parameters ()
     :precondition (and (clear-loc_2_7 ) (at-loc_2_6 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_7 )
        (clear-loc_2_6 ))
    )


    (:action move-loc_2_7-loc_2_6
     :parameters ()
     :precondition (and (clear-loc_2_6 ) (at-loc_2_7 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_6 )
        (clear-loc_2_7 ))
    )


    (:action move-loc_2_7-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_2_7 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_2_7 ))
    )


    (:action move-loc_2_8-loc_2_7
     :parameters ()
     :precondition (and (clear-loc_2_7 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_7 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_2_8-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_2_9-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_2_9-loc_2_10
     :parameters ()
     :precondition (and (clear-loc_2_10 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_2_10 ))
        (at-loc_2_10 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_2_10-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_2_10 ))
     :effect (and
        (not (at-loc_2_10 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_2_10 ))
    )


    (:action move-loc_2_12-loc_2_13
     :parameters ()
     :precondition (and (clear-loc_2_13 ) (at-loc_2_12 ))
     :effect (and
        (not (at-loc_2_12 ))
        (not (clear-loc_2_13 ))
        (at-loc_2_13 )
        (clear-loc_2_12 ))
    )


    (:action move-loc_2_13-loc_2_12
     :parameters ()
     :precondition (and (clear-loc_2_12 ) (at-loc_2_13 ))
     :effect (and
        (not (at-loc_2_13 ))
        (not (clear-loc_2_12 ))
        (at-loc_2_12 )
        (clear-loc_2_13 ))
    )


    (:action move-loc_3_0-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_3_0 ))
     :effect (and
        (not (at-loc_3_0 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_3_0 ))
    )


    (:action move-loc_3_1-loc_3_0
     :parameters ()
     :precondition (and (clear-loc_3_0 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_3_0 ))
        (at-loc_3_0 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_8-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_3_9-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_3_9-loc_3_10
     :parameters ()
     :precondition (and (clear-loc_3_10 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_10 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_3_10-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_3_10 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_3_10 ))
    )


    (:action move-loc_3_10-loc_3_11
     :parameters ()
     :precondition (and (clear-loc_3_11 ) (at-loc_3_10 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (clear-loc_3_11 ))
        (at-loc_3_11 )
        (clear-loc_3_10 ))
    )


    (:action move-loc_3_11-loc_3_10
     :parameters ()
     :precondition (and (clear-loc_3_10 ) (at-loc_3_11 ))
     :effect (and
        (not (at-loc_3_11 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_10 )
        (clear-loc_3_11 ))
    )


    (:action move-loc_3_11-loc_3_12
     :parameters ()
     :precondition (and (clear-loc_3_12 ) (at-loc_3_11 ))
     :effect (and
        (not (at-loc_3_11 ))
        (not (clear-loc_3_12 ))
        (at-loc_3_12 )
        (clear-loc_3_11 ))
    )


    (:action move-loc_3_12-loc_3_11
     :parameters ()
     :precondition (and (clear-loc_3_11 ) (at-loc_3_12 ))
     :effect (and
        (not (at-loc_3_12 ))
        (not (clear-loc_3_11 ))
        (at-loc_3_11 )
        (clear-loc_3_12 ))
    )


    (:action move-loc_3_12-loc_3_13
     :parameters ()
     :precondition (and (clear-loc_3_13 ) (at-loc_3_12 ))
     :effect (and
        (not (at-loc_3_12 ))
        (not (clear-loc_3_13 ))
        (at-loc_3_13 )
        (clear-loc_3_12 ))
    )


    (:action move-loc_3_13-loc_3_12
     :parameters ()
     :precondition (and (clear-loc_3_12 ) (at-loc_3_13 ))
     :effect (and
        (not (at-loc_3_13 ))
        (not (clear-loc_3_12 ))
        (at-loc_3_12 )
        (clear-loc_3_13 ))
    )


    (:action move-loc_4_3-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_4_4-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_4_6-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_4_7-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_4_9-loc_4_10
     :parameters ()
     :precondition (and (clear-loc_4_10 ) (at-loc_4_9 ))
     :effect (and
        (not (at-loc_4_9 ))
        (not (clear-loc_4_10 ))
        (at-loc_4_10 )
        (clear-loc_4_9 ))
    )


    (:action move-loc_4_10-loc_4_9
     :parameters ()
     :precondition (and (clear-loc_4_9 ) (at-loc_4_10 ))
     :effect (and
        (not (at-loc_4_10 ))
        (not (clear-loc_4_9 ))
        (at-loc_4_9 )
        (clear-loc_4_10 ))
    )


    (:action move-loc_4_12-loc_4_13
     :parameters ()
     :precondition (and (clear-loc_4_13 ) (at-loc_4_12 ))
     :effect (and
        (not (at-loc_4_12 ))
        (not (clear-loc_4_13 ))
        (at-loc_4_13 )
        (clear-loc_4_12 ))
    )


    (:action move-loc_4_13-loc_4_12
     :parameters ()
     :precondition (and (clear-loc_4_12 ) (at-loc_4_13 ))
     :effect (and
        (not (at-loc_4_13 ))
        (not (clear-loc_4_12 ))
        (at-loc_4_12 )
        (clear-loc_4_13 ))
    )


    (:action move-loc_5_1-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_5_2-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_5_2-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_5_3-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_5_3-loc_5_4
     :parameters ()
     :precondition (and (clear-loc_5_4 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_4 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_5_4-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_5_4 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_5_4 ))
    )


    (:action move-loc_5_4-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_5_4 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_5_4 ))
    )


    (:action move-loc_5_5-loc_5_4
     :parameters ()
     :precondition (and (clear-loc_5_4 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_4 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_5_5-loc_5_6
     :parameters ()
     :precondition (and (clear-loc_5_6 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_6 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_5_6-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_5_6 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_5_6 ))
    )


    (:action move-loc_5_6-loc_5_7
     :parameters ()
     :precondition (and (clear-loc_5_7 ) (at-loc_5_6 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_7 )
        (clear-loc_5_6 ))
    )


    (:action move-loc_5_7-loc_5_6
     :parameters ()
     :precondition (and (clear-loc_5_6 ) (at-loc_5_7 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_6 )
        (clear-loc_5_7 ))
    )


    (:action move-loc_5_7-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_5_7 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_5_7 ))
    )


    (:action move-loc_5_8-loc_5_7
     :parameters ()
     :precondition (and (clear-loc_5_7 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_7 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_5_8-loc_5_9
     :parameters ()
     :precondition (and (clear-loc_5_9 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_9 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_5_9-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_5_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_5_9 ))
    )


    (:action move-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_6_4-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_4-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_5-loc_6_6
     :parameters ()
     :precondition (and (clear-loc_6_6 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_6 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_6-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_6_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_6_6 ))
    )


    (:action move-loc_6_8-loc_6_9
     :parameters ()
     :precondition (and (clear-loc_6_9 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_9 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_6_9-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_6_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_6_9 ))
    )


    (:action move-loc_6_11-loc_6_12
     :parameters ()
     :precondition (and (clear-loc_6_12 ) (at-loc_6_11 ))
     :effect (and
        (not (at-loc_6_11 ))
        (not (clear-loc_6_12 ))
        (at-loc_6_12 )
        (clear-loc_6_11 ))
    )


    (:action move-loc_6_12-loc_6_11
     :parameters ()
     :precondition (and (clear-loc_6_11 ) (at-loc_6_12 ))
     :effect (and
        (not (at-loc_6_12 ))
        (not (clear-loc_6_11 ))
        (at-loc_6_11 )
        (clear-loc_6_12 ))
    )


    (:action move-loc_6_12-loc_6_13
     :parameters ()
     :precondition (and (clear-loc_6_13 ) (at-loc_6_12 ))
     :effect (and
        (not (at-loc_6_12 ))
        (not (clear-loc_6_13 ))
        (at-loc_6_13 )
        (clear-loc_6_12 ))
    )


    (:action move-loc_6_13-loc_6_12
     :parameters ()
     :precondition (and (clear-loc_6_12 ) (at-loc_6_13 ))
     :effect (and
        (not (at-loc_6_13 ))
        (not (clear-loc_6_12 ))
        (at-loc_6_12 )
        (clear-loc_6_13 ))
    )


    (:action move-loc_6_13-loc_6_14
     :parameters ()
     :precondition (and (clear-loc_6_14 ) (at-loc_6_13 ))
     :effect (and
        (not (at-loc_6_13 ))
        (not (clear-loc_6_14 ))
        (at-loc_6_14 )
        (clear-loc_6_13 ))
    )


    (:action move-loc_6_14-loc_6_13
     :parameters ()
     :precondition (and (clear-loc_6_13 ) (at-loc_6_14 ))
     :effect (and
        (not (at-loc_6_14 ))
        (not (clear-loc_6_13 ))
        (at-loc_6_13 )
        (clear-loc_6_14 ))
    )


    (:action move-loc_7_0-loc_7_1
     :parameters ()
     :precondition (and (clear-loc_7_1 ) (at-loc_7_0 ))
     :effect (and
        (not (at-loc_7_0 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_1 )
        (clear-loc_7_0 ))
    )


    (:action move-loc_7_1-loc_7_0
     :parameters ()
     :precondition (and (clear-loc_7_0 ) (at-loc_7_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (clear-loc_7_0 ))
        (at-loc_7_0 )
        (clear-loc_7_1 ))
    )


    (:action move-loc_7_11-loc_7_12
     :parameters ()
     :precondition (and (clear-loc_7_12 ) (at-loc_7_11 ))
     :effect (and
        (not (at-loc_7_11 ))
        (not (clear-loc_7_12 ))
        (at-loc_7_12 )
        (clear-loc_7_11 ))
    )


    (:action move-loc_7_12-loc_7_11
     :parameters ()
     :precondition (and (clear-loc_7_11 ) (at-loc_7_12 ))
     :effect (and
        (not (at-loc_7_12 ))
        (not (clear-loc_7_11 ))
        (at-loc_7_11 )
        (clear-loc_7_12 ))
    )


    (:action move-loc_7_12-loc_7_13
     :parameters ()
     :precondition (and (clear-loc_7_13 ) (at-loc_7_12 ))
     :effect (and
        (not (at-loc_7_12 ))
        (not (clear-loc_7_13 ))
        (at-loc_7_13 )
        (clear-loc_7_12 ))
    )


    (:action move-loc_7_13-loc_7_12
     :parameters ()
     :precondition (and (clear-loc_7_12 ) (at-loc_7_13 ))
     :effect (and
        (not (at-loc_7_13 ))
        (not (clear-loc_7_12 ))
        (at-loc_7_12 )
        (clear-loc_7_13 ))
    )


    (:action move-loc_7_13-loc_7_14
     :parameters ()
     :precondition (and (clear-loc_7_14 ) (at-loc_7_13 ))
     :effect (and
        (not (at-loc_7_13 ))
        (not (clear-loc_7_14 ))
        (at-loc_7_14 )
        (clear-loc_7_13 ))
    )


    (:action move-loc_7_14-loc_7_13
     :parameters ()
     :precondition (and (clear-loc_7_13 ) (at-loc_7_14 ))
     :effect (and
        (not (at-loc_7_14 ))
        (not (clear-loc_7_13 ))
        (at-loc_7_13 )
        (clear-loc_7_14 ))
    )


    (:action push-loc_0_0-loc_1_0
     :parameters ()
     :precondition (and (and (clear-loc_2_0 ) (at-loc_0_0 )) (box-loc_1_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (box-loc_1_0 ))
        (not (clear-loc_2_0 ))
        (at-loc_1_0 )
        (box-loc_2_0 )
        (clear-loc_0_0 ))
    )


    (:action push-loc_2_0-loc_1_0
     :parameters ()
     :precondition (and (and (clear-loc_0_0 ) (at-loc_2_0 )) (box-loc_1_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (box-loc_1_0 ))
        (not (clear-loc_0_0 ))
        (at-loc_1_0 )
        (box-loc_0_0 )
        (clear-loc_2_0 ))
    )


    (:action push-loc_0_1-loc_1_1
     :parameters ()
     :precondition (and (and (clear-loc_2_1 ) (at-loc_0_1 )) (box-loc_1_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (box-loc_1_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_1_1 )
        (box-loc_2_1 )
        (clear-loc_0_1 ))
    )


    (:action push-loc_2_1-loc_1_1
     :parameters ()
     :precondition (and (and (clear-loc_0_1 ) (at-loc_2_1 )) (box-loc_1_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (box-loc_1_1 ))
        (not (clear-loc_0_1 ))
        (at-loc_1_1 )
        (box-loc_0_1 )
        (clear-loc_2_1 ))
    )


    (:action push-loc_1_0-loc_2_0
     :parameters ()
     :precondition (and (and (clear-loc_3_0 ) (at-loc_1_0 )) (box-loc_2_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (box-loc_2_0 ))
        (not (clear-loc_3_0 ))
        (at-loc_2_0 )
        (box-loc_3_0 )
        (clear-loc_1_0 ))
    )


    (:action push-loc_3_0-loc_2_0
     :parameters ()
     :precondition (and (and (clear-loc_1_0 ) (at-loc_3_0 )) (box-loc_2_0 ))
     :effect (and
        (not (at-loc_3_0 ))
        (not (box-loc_2_0 ))
        (not (clear-loc_1_0 ))
        (at-loc_2_0 )
        (box-loc_1_0 )
        (clear-loc_3_0 ))
    )


    (:action push-loc_1_1-loc_2_1
     :parameters ()
     :precondition (and (and (clear-loc_3_1 ) (at-loc_1_1 )) (box-loc_2_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (box-loc_2_1 ))
        (not (clear-loc_3_1 ))
        (at-loc_2_1 )
        (box-loc_3_1 )
        (clear-loc_1_1 ))
    )


    (:action push-loc_3_1-loc_2_1
     :parameters ()
     :precondition (and (and (clear-loc_1_1 ) (at-loc_3_1 )) (box-loc_2_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (box-loc_2_1 ))
        (not (clear-loc_1_1 ))
        (at-loc_2_1 )
        (box-loc_1_1 )
        (clear-loc_3_1 ))
    )


    (:action push-loc_1_10-loc_2_10
     :parameters ()
     :precondition (and (and (clear-loc_3_10 ) (at-loc_1_10 )) (box-loc_2_10 ))
     :effect (and
        (not (at-loc_1_10 ))
        (not (box-loc_2_10 ))
        (not (clear-loc_3_10 ))
        (at-loc_2_10 )
        (box-loc_3_10 )
        (clear-loc_1_10 ))
    )


    (:action push-loc_3_10-loc_2_10
     :parameters ()
     :precondition (and (and (clear-loc_1_10 ) (at-loc_3_10 )) (box-loc_2_10 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (box-loc_2_10 ))
        (not (clear-loc_1_10 ))
        (at-loc_2_10 )
        (box-loc_1_10 )
        (clear-loc_3_10 ))
    )


    (:action push-loc_2_3-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_2_3 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_3_3 )
        (box-loc_4_3 )
        (clear-loc_2_3 ))
    )


    (:action push-loc_4_3-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_2_3 ) (at-loc_4_3 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_3_3 )
        (box-loc_2_3 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_2_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_3_4 )
        (box-loc_4_4 )
        (clear-loc_2_4 ))
    )


    (:action push-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_2_4 ) (at-loc_4_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_3_4 )
        (box-loc_2_4 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_2_9-loc_3_9
     :parameters ()
     :precondition (and (and (clear-loc_4_9 ) (at-loc_2_9 )) (box-loc_3_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (box-loc_3_9 ))
        (not (clear-loc_4_9 ))
        (at-loc_3_9 )
        (box-loc_4_9 )
        (clear-loc_2_9 ))
    )


    (:action push-loc_4_9-loc_3_9
     :parameters ()
     :precondition (and (and (clear-loc_2_9 ) (at-loc_4_9 )) (box-loc_3_9 ))
     :effect (and
        (not (at-loc_4_9 ))
        (not (box-loc_3_9 ))
        (not (clear-loc_2_9 ))
        (at-loc_3_9 )
        (box-loc_2_9 )
        (clear-loc_4_9 ))
    )


    (:action push-loc_2_10-loc_3_10
     :parameters ()
     :precondition (and (and (clear-loc_4_10 ) (at-loc_2_10 )) (box-loc_3_10 ))
     :effect (and
        (not (at-loc_2_10 ))
        (not (box-loc_3_10 ))
        (not (clear-loc_4_10 ))
        (at-loc_3_10 )
        (box-loc_4_10 )
        (clear-loc_2_10 ))
    )


    (:action push-loc_4_10-loc_3_10
     :parameters ()
     :precondition (and (and (clear-loc_2_10 ) (at-loc_4_10 )) (box-loc_3_10 ))
     :effect (and
        (not (at-loc_4_10 ))
        (not (box-loc_3_10 ))
        (not (clear-loc_2_10 ))
        (at-loc_3_10 )
        (box-loc_2_10 )
        (clear-loc_4_10 ))
    )


    (:action push-loc_2_12-loc_3_12
     :parameters ()
     :precondition (and (and (clear-loc_4_12 ) (at-loc_2_12 )) (box-loc_3_12 ))
     :effect (and
        (not (at-loc_2_12 ))
        (not (box-loc_3_12 ))
        (not (clear-loc_4_12 ))
        (at-loc_3_12 )
        (box-loc_4_12 )
        (clear-loc_2_12 ))
    )


    (:action push-loc_4_12-loc_3_12
     :parameters ()
     :precondition (and (and (clear-loc_2_12 ) (at-loc_4_12 )) (box-loc_3_12 ))
     :effect (and
        (not (at-loc_4_12 ))
        (not (box-loc_3_12 ))
        (not (clear-loc_2_12 ))
        (at-loc_3_12 )
        (box-loc_2_12 )
        (clear-loc_4_12 ))
    )


    (:action push-loc_2_13-loc_3_13
     :parameters ()
     :precondition (and (and (clear-loc_4_13 ) (at-loc_2_13 )) (box-loc_3_13 ))
     :effect (and
        (not (at-loc_2_13 ))
        (not (box-loc_3_13 ))
        (not (clear-loc_4_13 ))
        (at-loc_3_13 )
        (box-loc_4_13 )
        (clear-loc_2_13 ))
    )


    (:action push-loc_4_13-loc_3_13
     :parameters ()
     :precondition (and (and (clear-loc_2_13 ) (at-loc_4_13 )) (box-loc_3_13 ))
     :effect (and
        (not (at-loc_4_13 ))
        (not (box-loc_3_13 ))
        (not (clear-loc_2_13 ))
        (at-loc_3_13 )
        (box-loc_2_13 )
        (clear-loc_4_13 ))
    )


    (:action push-loc_3_3-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_5_3 ) (at-loc_3_3 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_4_3 )
        (box-loc_5_3 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_5_3-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_5_3 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_4_3 )
        (box-loc_3_3 )
        (clear-loc_5_3 ))
    )


    (:action push-loc_3_4-loc_4_4
     :parameters ()
     :precondition (and (and (clear-loc_5_4 ) (at-loc_3_4 )) (box-loc_4_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_4_4 ))
        (not (clear-loc_5_4 ))
        (at-loc_4_4 )
        (box-loc_5_4 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_5_4-loc_4_4
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_5_4 )) (box-loc_4_4 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (box-loc_4_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_4_4 )
        (box-loc_3_4 )
        (clear-loc_5_4 ))
    )


    (:action push-loc_3_9-loc_4_9
     :parameters ()
     :precondition (and (and (clear-loc_5_9 ) (at-loc_3_9 )) (box-loc_4_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (box-loc_4_9 ))
        (not (clear-loc_5_9 ))
        (at-loc_4_9 )
        (box-loc_5_9 )
        (clear-loc_3_9 ))
    )


    (:action push-loc_5_9-loc_4_9
     :parameters ()
     :precondition (and (and (clear-loc_3_9 ) (at-loc_5_9 )) (box-loc_4_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (box-loc_4_9 ))
        (not (clear-loc_3_9 ))
        (at-loc_4_9 )
        (box-loc_3_9 )
        (clear-loc_5_9 ))
    )


    (:action push-loc_4_3-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_4_3 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_5_3 )
        (box-loc_6_3 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_6_3-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_6_3 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_5_3 )
        (box-loc_4_3 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_4_4-loc_5_4
     :parameters ()
     :precondition (and (and (clear-loc_6_4 ) (at-loc_4_4 )) (box-loc_5_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_5_4 ))
        (not (clear-loc_6_4 ))
        (at-loc_5_4 )
        (box-loc_6_4 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_6_4-loc_5_4
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_6_4 )) (box-loc_5_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (box-loc_5_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_5_4 )
        (box-loc_4_4 )
        (clear-loc_6_4 ))
    )


    (:action push-loc_4_6-loc_5_6
     :parameters ()
     :precondition (and (and (clear-loc_6_6 ) (at-loc_4_6 )) (box-loc_5_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (box-loc_5_6 ))
        (not (clear-loc_6_6 ))
        (at-loc_5_6 )
        (box-loc_6_6 )
        (clear-loc_4_6 ))
    )


    (:action push-loc_6_6-loc_5_6
     :parameters ()
     :precondition (and (and (clear-loc_4_6 ) (at-loc_6_6 )) (box-loc_5_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (box-loc_5_6 ))
        (not (clear-loc_4_6 ))
        (at-loc_5_6 )
        (box-loc_4_6 )
        (clear-loc_6_6 ))
    )


    (:action push-loc_4_9-loc_5_9
     :parameters ()
     :precondition (and (and (clear-loc_6_9 ) (at-loc_4_9 )) (box-loc_5_9 ))
     :effect (and
        (not (at-loc_4_9 ))
        (not (box-loc_5_9 ))
        (not (clear-loc_6_9 ))
        (at-loc_5_9 )
        (box-loc_6_9 )
        (clear-loc_4_9 ))
    )


    (:action push-loc_6_9-loc_5_9
     :parameters ()
     :precondition (and (and (clear-loc_4_9 ) (at-loc_6_9 )) (box-loc_5_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (box-loc_5_9 ))
        (not (clear-loc_4_9 ))
        (at-loc_5_9 )
        (box-loc_4_9 )
        (clear-loc_6_9 ))
    )


    (:action push-loc_0_0-loc_0_1
     :parameters ()
     :precondition (and (and (clear-loc_0_2 ) (at-loc_0_0 )) (box-loc_0_1 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (box-loc_0_1 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_1 )
        (box-loc_0_2 )
        (clear-loc_0_0 ))
    )


    (:action push-loc_0_2-loc_0_1
     :parameters ()
     :precondition (and (and (clear-loc_0_0 ) (at-loc_0_2 )) (box-loc_0_1 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (box-loc_0_1 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_1 )
        (box-loc_0_0 )
        (clear-loc_0_2 ))
    )


    (:action push-loc_0_1-loc_0_2
     :parameters ()
     :precondition (and (and (clear-loc_0_3 ) (at-loc_0_1 )) (box-loc_0_2 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (box-loc_0_2 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_2 )
        (box-loc_0_3 )
        (clear-loc_0_1 ))
    )


    (:action push-loc_0_3-loc_0_2
     :parameters ()
     :precondition (and (and (clear-loc_0_1 ) (at-loc_0_3 )) (box-loc_0_2 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (box-loc_0_2 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_2 )
        (box-loc_0_1 )
        (clear-loc_0_3 ))
    )


    (:action push-loc_0_2-loc_0_3
     :parameters ()
     :precondition (and (and (clear-loc_0_4 ) (at-loc_0_2 )) (box-loc_0_3 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (box-loc_0_3 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_3 )
        (box-loc_0_4 )
        (clear-loc_0_2 ))
    )


    (:action push-loc_0_4-loc_0_3
     :parameters ()
     :precondition (and (and (clear-loc_0_2 ) (at-loc_0_4 )) (box-loc_0_3 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (box-loc_0_3 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_3 )
        (box-loc_0_2 )
        (clear-loc_0_4 ))
    )


    (:action push-loc_0_3-loc_0_4
     :parameters ()
     :precondition (and (and (clear-loc_0_5 ) (at-loc_0_3 )) (box-loc_0_4 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (box-loc_0_4 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_4 )
        (box-loc_0_5 )
        (clear-loc_0_3 ))
    )


    (:action push-loc_0_5-loc_0_4
     :parameters ()
     :precondition (and (and (clear-loc_0_3 ) (at-loc_0_5 )) (box-loc_0_4 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (box-loc_0_4 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_4 )
        (box-loc_0_3 )
        (clear-loc_0_5 ))
    )


    (:action push-loc_0_4-loc_0_5
     :parameters ()
     :precondition (and (and (clear-loc_0_6 ) (at-loc_0_4 )) (box-loc_0_5 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (box-loc_0_5 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_5 )
        (box-loc_0_6 )
        (clear-loc_0_4 ))
    )


    (:action push-loc_0_6-loc_0_5
     :parameters ()
     :precondition (and (and (clear-loc_0_4 ) (at-loc_0_6 )) (box-loc_0_5 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (box-loc_0_5 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_5 )
        (box-loc_0_4 )
        (clear-loc_0_6 ))
    )


    (:action push-loc_0_5-loc_0_6
     :parameters ()
     :precondition (and (and (clear-loc_0_7 ) (at-loc_0_5 )) (box-loc_0_6 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (box-loc_0_6 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_6 )
        (box-loc_0_7 )
        (clear-loc_0_5 ))
    )


    (:action push-loc_0_7-loc_0_6
     :parameters ()
     :precondition (and (and (clear-loc_0_5 ) (at-loc_0_7 )) (box-loc_0_6 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (box-loc_0_6 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_6 )
        (box-loc_0_5 )
        (clear-loc_0_7 ))
    )


    (:action push-loc_0_6-loc_0_7
     :parameters ()
     :precondition (and (and (clear-loc_0_8 ) (at-loc_0_6 )) (box-loc_0_7 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (box-loc_0_7 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_7 )
        (box-loc_0_8 )
        (clear-loc_0_6 ))
    )


    (:action push-loc_0_8-loc_0_7
     :parameters ()
     :precondition (and (and (clear-loc_0_6 ) (at-loc_0_8 )) (box-loc_0_7 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (box-loc_0_7 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_7 )
        (box-loc_0_6 )
        (clear-loc_0_8 ))
    )


    (:action push-loc_0_12-loc_0_13
     :parameters ()
     :precondition (and (and (clear-loc_0_14 ) (at-loc_0_12 )) (box-loc_0_13 ))
     :effect (and
        (not (at-loc_0_12 ))
        (not (box-loc_0_13 ))
        (not (clear-loc_0_14 ))
        (at-loc_0_13 )
        (box-loc_0_14 )
        (clear-loc_0_12 ))
    )


    (:action push-loc_0_14-loc_0_13
     :parameters ()
     :precondition (and (and (clear-loc_0_12 ) (at-loc_0_14 )) (box-loc_0_13 ))
     :effect (and
        (not (at-loc_0_14 ))
        (not (box-loc_0_13 ))
        (not (clear-loc_0_12 ))
        (at-loc_0_13 )
        (box-loc_0_12 )
        (clear-loc_0_14 ))
    )


    (:action push-loc_2_3-loc_2_4
     :parameters ()
     :precondition (and (and (clear-loc_2_5 ) (at-loc_2_3 )) (box-loc_2_4 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (box-loc_2_4 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_4 )
        (box-loc_2_5 )
        (clear-loc_2_3 ))
    )


    (:action push-loc_2_5-loc_2_4
     :parameters ()
     :precondition (and (and (clear-loc_2_3 ) (at-loc_2_5 )) (box-loc_2_4 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (box-loc_2_4 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_4 )
        (box-loc_2_3 )
        (clear-loc_2_5 ))
    )


    (:action push-loc_2_4-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_2_6 ) (at-loc_2_4 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_5 )
        (box-loc_2_6 )
        (clear-loc_2_4 ))
    )


    (:action push-loc_2_6-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_2_4 ) (at-loc_2_6 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_5 )
        (box-loc_2_4 )
        (clear-loc_2_6 ))
    )


    (:action push-loc_2_5-loc_2_6
     :parameters ()
     :precondition (and (and (clear-loc_2_7 ) (at-loc_2_5 )) (box-loc_2_6 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (box-loc_2_6 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_6 )
        (box-loc_2_7 )
        (clear-loc_2_5 ))
    )


    (:action push-loc_2_7-loc_2_6
     :parameters ()
     :precondition (and (and (clear-loc_2_5 ) (at-loc_2_7 )) (box-loc_2_6 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (box-loc_2_6 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_6 )
        (box-loc_2_5 )
        (clear-loc_2_7 ))
    )


    (:action push-loc_2_6-loc_2_7
     :parameters ()
     :precondition (and (and (clear-loc_2_8 ) (at-loc_2_6 )) (box-loc_2_7 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (box-loc_2_7 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_7 )
        (box-loc_2_8 )
        (clear-loc_2_6 ))
    )


    (:action push-loc_2_8-loc_2_7
     :parameters ()
     :precondition (and (and (clear-loc_2_6 ) (at-loc_2_8 )) (box-loc_2_7 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (box-loc_2_7 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_7 )
        (box-loc_2_6 )
        (clear-loc_2_8 ))
    )


    (:action push-loc_2_7-loc_2_8
     :parameters ()
     :precondition (and (and (clear-loc_2_9 ) (at-loc_2_7 )) (box-loc_2_8 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (box-loc_2_8 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_8 )
        (box-loc_2_9 )
        (clear-loc_2_7 ))
    )


    (:action push-loc_2_9-loc_2_8
     :parameters ()
     :precondition (and (and (clear-loc_2_7 ) (at-loc_2_9 )) (box-loc_2_8 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (box-loc_2_8 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_8 )
        (box-loc_2_7 )
        (clear-loc_2_9 ))
    )


    (:action push-loc_2_8-loc_2_9
     :parameters ()
     :precondition (and (and (clear-loc_2_10 ) (at-loc_2_8 )) (box-loc_2_9 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (box-loc_2_9 ))
        (not (clear-loc_2_10 ))
        (at-loc_2_9 )
        (box-loc_2_10 )
        (clear-loc_2_8 ))
    )


    (:action push-loc_2_10-loc_2_9
     :parameters ()
     :precondition (and (and (clear-loc_2_8 ) (at-loc_2_10 )) (box-loc_2_9 ))
     :effect (and
        (not (at-loc_2_10 ))
        (not (box-loc_2_9 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_9 )
        (box-loc_2_8 )
        (clear-loc_2_10 ))
    )


    (:action push-loc_3_8-loc_3_9
     :parameters ()
     :precondition (and (and (clear-loc_3_10 ) (at-loc_3_8 )) (box-loc_3_9 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (box-loc_3_9 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_9 )
        (box-loc_3_10 )
        (clear-loc_3_8 ))
    )


    (:action push-loc_3_10-loc_3_9
     :parameters ()
     :precondition (and (and (clear-loc_3_8 ) (at-loc_3_10 )) (box-loc_3_9 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (box-loc_3_9 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_9 )
        (box-loc_3_8 )
        (clear-loc_3_10 ))
    )


    (:action push-loc_3_9-loc_3_10
     :parameters ()
     :precondition (and (and (clear-loc_3_11 ) (at-loc_3_9 )) (box-loc_3_10 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (box-loc_3_10 ))
        (not (clear-loc_3_11 ))
        (at-loc_3_10 )
        (box-loc_3_11 )
        (clear-loc_3_9 ))
    )


    (:action push-loc_3_11-loc_3_10
     :parameters ()
     :precondition (and (and (clear-loc_3_9 ) (at-loc_3_11 )) (box-loc_3_10 ))
     :effect (and
        (not (at-loc_3_11 ))
        (not (box-loc_3_10 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_10 )
        (box-loc_3_9 )
        (clear-loc_3_11 ))
    )


    (:action push-loc_3_10-loc_3_11
     :parameters ()
     :precondition (and (and (clear-loc_3_12 ) (at-loc_3_10 )) (box-loc_3_11 ))
     :effect (and
        (not (at-loc_3_10 ))
        (not (box-loc_3_11 ))
        (not (clear-loc_3_12 ))
        (at-loc_3_11 )
        (box-loc_3_12 )
        (clear-loc_3_10 ))
    )


    (:action push-loc_3_12-loc_3_11
     :parameters ()
     :precondition (and (and (clear-loc_3_10 ) (at-loc_3_12 )) (box-loc_3_11 ))
     :effect (and
        (not (at-loc_3_12 ))
        (not (box-loc_3_11 ))
        (not (clear-loc_3_10 ))
        (at-loc_3_11 )
        (box-loc_3_10 )
        (clear-loc_3_12 ))
    )


    (:action push-loc_3_11-loc_3_12
     :parameters ()
     :precondition (and (and (clear-loc_3_13 ) (at-loc_3_11 )) (box-loc_3_12 ))
     :effect (and
        (not (at-loc_3_11 ))
        (not (box-loc_3_12 ))
        (not (clear-loc_3_13 ))
        (at-loc_3_12 )
        (box-loc_3_13 )
        (clear-loc_3_11 ))
    )


    (:action push-loc_3_13-loc_3_12
     :parameters ()
     :precondition (and (and (clear-loc_3_11 ) (at-loc_3_13 )) (box-loc_3_12 ))
     :effect (and
        (not (at-loc_3_13 ))
        (not (box-loc_3_12 ))
        (not (clear-loc_3_11 ))
        (at-loc_3_12 )
        (box-loc_3_11 )
        (clear-loc_3_13 ))
    )


    (:action push-loc_5_1-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_5_3 ) (at-loc_5_1 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_2 )
        (box-loc_5_3 )
        (clear-loc_5_1 ))
    )


    (:action push-loc_5_3-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_5_1 ) (at-loc_5_3 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_2 )
        (box-loc_5_1 )
        (clear-loc_5_3 ))
    )


    (:action push-loc_5_2-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_5_4 ) (at-loc_5_2 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_3 )
        (box-loc_5_4 )
        (clear-loc_5_2 ))
    )


    (:action push-loc_5_4-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_5_2 ) (at-loc_5_4 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_3 )
        (box-loc_5_2 )
        (clear-loc_5_4 ))
    )


    (:action push-loc_5_3-loc_5_4
     :parameters ()
     :precondition (and (and (clear-loc_5_5 ) (at-loc_5_3 )) (box-loc_5_4 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (box-loc_5_4 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_4 )
        (box-loc_5_5 )
        (clear-loc_5_3 ))
    )


    (:action push-loc_5_5-loc_5_4
     :parameters ()
     :precondition (and (and (clear-loc_5_3 ) (at-loc_5_5 )) (box-loc_5_4 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (box-loc_5_4 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_4 )
        (box-loc_5_3 )
        (clear-loc_5_5 ))
    )


    (:action push-loc_5_4-loc_5_5
     :parameters ()
     :precondition (and (and (clear-loc_5_6 ) (at-loc_5_4 )) (box-loc_5_5 ))
     :effect (and
        (not (at-loc_5_4 ))
        (not (box-loc_5_5 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_5 )
        (box-loc_5_6 )
        (clear-loc_5_4 ))
    )


    (:action push-loc_5_6-loc_5_5
     :parameters ()
     :precondition (and (and (clear-loc_5_4 ) (at-loc_5_6 )) (box-loc_5_5 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (box-loc_5_5 ))
        (not (clear-loc_5_4 ))
        (at-loc_5_5 )
        (box-loc_5_4 )
        (clear-loc_5_6 ))
    )


    (:action push-loc_5_5-loc_5_6
     :parameters ()
     :precondition (and (and (clear-loc_5_7 ) (at-loc_5_5 )) (box-loc_5_6 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (box-loc_5_6 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_6 )
        (box-loc_5_7 )
        (clear-loc_5_5 ))
    )


    (:action push-loc_5_7-loc_5_6
     :parameters ()
     :precondition (and (and (clear-loc_5_5 ) (at-loc_5_7 )) (box-loc_5_6 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (box-loc_5_6 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_6 )
        (box-loc_5_5 )
        (clear-loc_5_7 ))
    )


    (:action push-loc_5_6-loc_5_7
     :parameters ()
     :precondition (and (and (clear-loc_5_8 ) (at-loc_5_6 )) (box-loc_5_7 ))
     :effect (and
        (not (at-loc_5_6 ))
        (not (box-loc_5_7 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_7 )
        (box-loc_5_8 )
        (clear-loc_5_6 ))
    )


    (:action push-loc_5_8-loc_5_7
     :parameters ()
     :precondition (and (and (clear-loc_5_6 ) (at-loc_5_8 )) (box-loc_5_7 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (box-loc_5_7 ))
        (not (clear-loc_5_6 ))
        (at-loc_5_7 )
        (box-loc_5_6 )
        (clear-loc_5_8 ))
    )


    (:action push-loc_5_7-loc_5_8
     :parameters ()
     :precondition (and (and (clear-loc_5_9 ) (at-loc_5_7 )) (box-loc_5_8 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (box-loc_5_8 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_8 )
        (box-loc_5_9 )
        (clear-loc_5_7 ))
    )


    (:action push-loc_5_9-loc_5_8
     :parameters ()
     :precondition (and (and (clear-loc_5_7 ) (at-loc_5_9 )) (box-loc_5_8 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (box-loc_5_8 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_8 )
        (box-loc_5_7 )
        (clear-loc_5_9 ))
    )


    (:action push-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_6_3 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_4 )
        (box-loc_6_5 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_6_5 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_4 )
        (box-loc_6_3 )
        (clear-loc_6_5 ))
    )


    (:action push-loc_6_4-loc_6_5
     :parameters ()
     :precondition (and (and (clear-loc_6_6 ) (at-loc_6_4 )) (box-loc_6_5 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (box-loc_6_5 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_5 )
        (box-loc_6_6 )
        (clear-loc_6_4 ))
    )


    (:action push-loc_6_6-loc_6_5
     :parameters ()
     :precondition (and (and (clear-loc_6_4 ) (at-loc_6_6 )) (box-loc_6_5 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (box-loc_6_5 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_5 )
        (box-loc_6_4 )
        (clear-loc_6_6 ))
    )


    (:action push-loc_6_11-loc_6_12
     :parameters ()
     :precondition (and (and (clear-loc_6_13 ) (at-loc_6_11 )) (box-loc_6_12 ))
     :effect (and
        (not (at-loc_6_11 ))
        (not (box-loc_6_12 ))
        (not (clear-loc_6_13 ))
        (at-loc_6_12 )
        (box-loc_6_13 )
        (clear-loc_6_11 ))
    )


    (:action push-loc_6_13-loc_6_12
     :parameters ()
     :precondition (and (and (clear-loc_6_11 ) (at-loc_6_13 )) (box-loc_6_12 ))
     :effect (and
        (not (at-loc_6_13 ))
        (not (box-loc_6_12 ))
        (not (clear-loc_6_11 ))
        (at-loc_6_12 )
        (box-loc_6_11 )
        (clear-loc_6_13 ))
    )


    (:action push-loc_6_12-loc_6_13
     :parameters ()
     :precondition (and (and (clear-loc_6_14 ) (at-loc_6_12 )) (box-loc_6_13 ))
     :effect (and
        (not (at-loc_6_12 ))
        (not (box-loc_6_13 ))
        (not (clear-loc_6_14 ))
        (at-loc_6_13 )
        (box-loc_6_14 )
        (clear-loc_6_12 ))
    )


    (:action push-loc_6_14-loc_6_13
     :parameters ()
     :precondition (and (and (clear-loc_6_12 ) (at-loc_6_14 )) (box-loc_6_13 ))
     :effect (and
        (not (at-loc_6_14 ))
        (not (box-loc_6_13 ))
        (not (clear-loc_6_12 ))
        (at-loc_6_13 )
        (box-loc_6_12 )
        (clear-loc_6_14 ))
    )


    (:action push-loc_7_11-loc_7_12
     :parameters ()
     :precondition (and (and (clear-loc_7_13 ) (at-loc_7_11 )) (box-loc_7_12 ))
     :effect (and
        (not (at-loc_7_11 ))
        (not (box-loc_7_12 ))
        (not (clear-loc_7_13 ))
        (at-loc_7_12 )
        (box-loc_7_13 )
        (clear-loc_7_11 ))
    )


    (:action push-loc_7_13-loc_7_12
     :parameters ()
     :precondition (and (and (clear-loc_7_11 ) (at-loc_7_13 )) (box-loc_7_12 ))
     :effect (and
        (not (at-loc_7_13 ))
        (not (box-loc_7_12 ))
        (not (clear-loc_7_11 ))
        (at-loc_7_12 )
        (box-loc_7_11 )
        (clear-loc_7_13 ))
    )


    (:action push-loc_7_12-loc_7_13
     :parameters ()
     :precondition (and (and (clear-loc_7_14 ) (at-loc_7_12 )) (box-loc_7_13 ))
     :effect (and
        (not (at-loc_7_12 ))
        (not (box-loc_7_13 ))
        (not (clear-loc_7_14 ))
        (at-loc_7_13 )
        (box-loc_7_14 )
        (clear-loc_7_12 ))
    )


    (:action push-loc_7_14-loc_7_13
     :parameters ()
     :precondition (and (and (clear-loc_7_12 ) (at-loc_7_14 )) (box-loc_7_13 ))
     :effect (and
        (not (at-loc_7_14 ))
        (not (box-loc_7_13 ))
        (not (clear-loc_7_12 ))
        (at-loc_7_13 )
        (box-loc_7_12 )
        (clear-loc_7_14 ))
    )

)