
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain Sokoban)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (at-loc_0_0 )
        (box-loc_0_0 )
        (clear-loc_0_0 )
        (at-loc_0_1 )
        (box-loc_0_1 )
        (clear-loc_0_1 )
        (at-loc_0_2 )
        (box-loc_0_2 )
        (clear-loc_0_2 )
        (at-loc_0_3 )
        (box-loc_0_3 )
        (clear-loc_0_3 )
        (at-loc_0_7 )
        (box-loc_0_7 )
        (clear-loc_0_7 )
        (at-loc_0_8 )
        (box-loc_0_8 )
        (clear-loc_0_8 )
        (at-loc_1_5 )
        (box-loc_1_5 )
        (clear-loc_1_5 )
        (at-loc_1_7 )
        (box-loc_1_7 )
        (clear-loc_1_7 )
        (at-loc_1_8 )
        (box-loc_1_8 )
        (clear-loc_1_8 )
        (at-loc_2_1 )
        (box-loc_2_1 )
        (clear-loc_2_1 )
        (at-loc_2_2 )
        (box-loc_2_2 )
        (clear-loc_2_2 )
        (at-loc_2_3 )
        (box-loc_2_3 )
        (clear-loc_2_3 )
        (at-loc_2_5 )
        (box-loc_2_5 )
        (clear-loc_2_5 )
        (at-loc_3_1 )
        (box-loc_3_1 )
        (clear-loc_3_1 )
        (at-loc_3_2 )
        (box-loc_3_2 )
        (clear-loc_3_2 )
        (at-loc_3_3 )
        (box-loc_3_3 )
        (clear-loc_3_3 )
        (at-loc_3_4 )
        (box-loc_3_4 )
        (clear-loc_3_4 )
        (at-loc_3_5 )
        (box-loc_3_5 )
        (clear-loc_3_5 )
        (at-loc_3_6 )
        (box-loc_3_6 )
        (clear-loc_3_6 )
        (at-loc_3_7 )
        (box-loc_3_7 )
        (clear-loc_3_7 )
        (at-loc_4_5 )
        (box-loc_4_5 )
        (clear-loc_4_5 )
        (at-loc_5_0 )
        (box-loc_5_0 )
        (clear-loc_5_0 )
        (at-loc_5_1 )
        (box-loc_5_1 )
        (clear-loc_5_1 )
        (at-loc_5_2 )
        (box-loc_5_2 )
        (clear-loc_5_2 )
        (at-loc_5_3 )
        (box-loc_5_3 )
        (clear-loc_5_3 )
        (at-loc_5_5 )
        (box-loc_5_5 )
        (clear-loc_5_5 )
        (at-loc_5_7 )
        (box-loc_5_7 )
        (clear-loc_5_7 )
        (at-loc_5_8 )
        (box-loc_5_8 )
        (clear-loc_5_8 )
        (at-loc_6_0 )
        (box-loc_6_0 )
        (clear-loc_6_0 )
        (at-loc_6_1 )
        (box-loc_6_1 )
        (clear-loc_6_1 )
        (at-loc_6_2 )
        (box-loc_6_2 )
        (clear-loc_6_2 )
        (at-loc_6_3 )
        (box-loc_6_3 )
        (clear-loc_6_3 )
        (at-loc_6_7 )
        (box-loc_6_7 )
        (clear-loc_6_7 )
        (at-loc_6_8 )
        (box-loc_6_8 )
        (clear-loc_6_8 )
    )

    (:functions
        
    )

    

    
    (:action move-loc_0_7-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_1_7-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_0_8-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_0_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_0_8 ))
    )


    (:action move-loc_1_8-loc_0_8
     :parameters ()
     :precondition (and (clear-loc_0_8 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_8 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_1_5-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_1_5 ))
     :effect (and
        (not (at-loc_1_5 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_1_5 ))
    )


    (:action move-loc_2_5-loc_1_5
     :parameters ()
     :precondition (and (clear-loc_1_5 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_1_5 ))
        (at-loc_1_5 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_2_1-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_3_1-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_2_2-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_3_2-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_2_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_3_3-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_2_5-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_3_5-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_3_5-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_4_5-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_4_5-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_5_5-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_5_0-loc_6_0
     :parameters ()
     :precondition (and (clear-loc_6_0 ) (at-loc_5_0 ))
     :effect (and
        (not (at-loc_5_0 ))
        (not (clear-loc_6_0 ))
        (at-loc_6_0 )
        (clear-loc_5_0 ))
    )


    (:action move-loc_6_0-loc_5_0
     :parameters ()
     :precondition (and (clear-loc_5_0 ) (at-loc_6_0 ))
     :effect (and
        (not (at-loc_6_0 ))
        (not (clear-loc_5_0 ))
        (at-loc_5_0 )
        (clear-loc_6_0 ))
    )


    (:action move-loc_5_1-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_6_1-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_5_2-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_6_2-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_5_3-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_6_3-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_5_7-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_5_7 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_5_7 ))
    )


    (:action move-loc_6_7-loc_5_7
     :parameters ()
     :precondition (and (clear-loc_5_7 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_7 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_5_8-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_6_8-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_0_0-loc_0_1
     :parameters ()
     :precondition (and (clear-loc_0_1 ) (at-loc_0_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_1 )
        (clear-loc_0_0 ))
    )


    (:action move-loc_0_1-loc_0_0
     :parameters ()
     :precondition (and (clear-loc_0_0 ) (at-loc_0_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_0 )
        (clear-loc_0_1 ))
    )


    (:action move-loc_0_1-loc_0_2
     :parameters ()
     :precondition (and (clear-loc_0_2 ) (at-loc_0_1 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_2 )
        (clear-loc_0_1 ))
    )


    (:action move-loc_0_2-loc_0_1
     :parameters ()
     :precondition (and (clear-loc_0_1 ) (at-loc_0_2 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_1 )
        (clear-loc_0_2 ))
    )


    (:action move-loc_0_2-loc_0_3
     :parameters ()
     :precondition (and (clear-loc_0_3 ) (at-loc_0_2 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_3 )
        (clear-loc_0_2 ))
    )


    (:action move-loc_0_3-loc_0_2
     :parameters ()
     :precondition (and (clear-loc_0_2 ) (at-loc_0_3 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_2 )
        (clear-loc_0_3 ))
    )


    (:action move-loc_0_7-loc_0_8
     :parameters ()
     :precondition (and (clear-loc_0_8 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_8 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_0_8-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_0_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_0_8 ))
    )


    (:action move-loc_1_7-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_1_8-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_2_1-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_2_2-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_2_2-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_2_3-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_3_1-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_3_2-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_3_2-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_3_3-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_4-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_3_5-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_3_6-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_3_6-loc_3_7
     :parameters ()
     :precondition (and (clear-loc_3_7 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_7 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_3_7-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_3_7 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_3_7 ))
    )


    (:action move-loc_5_0-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_5_0 ))
     :effect (and
        (not (at-loc_5_0 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_5_0 ))
    )


    (:action move-loc_5_1-loc_5_0
     :parameters ()
     :precondition (and (clear-loc_5_0 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_5_0 ))
        (at-loc_5_0 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_5_1-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_5_2-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_5_2-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_5_3-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_5_7-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_5_7 ))
     :effect (and
        (not (at-loc_5_7 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_5_7 ))
    )


    (:action move-loc_5_8-loc_5_7
     :parameters ()
     :precondition (and (clear-loc_5_7 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_5_7 ))
        (at-loc_5_7 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_6_0-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_6_0 ))
     :effect (and
        (not (at-loc_6_0 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_6_0 ))
    )


    (:action move-loc_6_1-loc_6_0
     :parameters ()
     :precondition (and (clear-loc_6_0 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_6_0 ))
        (at-loc_6_0 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_6_1-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_6_2-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_6_2-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_6_3-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_6_7-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_6_8-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_6_8 ))
    )


    (:action push-loc_1_5-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_1_5 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_1_5 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_2_5 )
        (box-loc_3_5 )
        (clear-loc_1_5 ))
    )


    (:action push-loc_3_5-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_1_5 ) (at-loc_3_5 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_1_5 ))
        (at-loc_2_5 )
        (box-loc_1_5 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_2_5-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_4_5 ) (at-loc_2_5 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_3_5 )
        (box-loc_4_5 )
        (clear-loc_2_5 ))
    )


    (:action push-loc_4_5-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_2_5 ) (at-loc_4_5 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_2_5 ))
        (at-loc_3_5 )
        (box-loc_2_5 )
        (clear-loc_4_5 ))
    )


    (:action push-loc_3_5-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_5_5 ) (at-loc_3_5 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_4_5 )
        (box-loc_5_5 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_5_5-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_5_5 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_4_5 )
        (box-loc_3_5 )
        (clear-loc_5_5 ))
    )


    (:action push-loc_0_0-loc_0_1
     :parameters ()
     :precondition (and (and (clear-loc_0_2 ) (at-loc_0_0 )) (box-loc_0_1 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (box-loc_0_1 ))
        (not (clear-loc_0_2 ))
        (at-loc_0_1 )
        (box-loc_0_2 )
        (clear-loc_0_0 ))
    )


    (:action push-loc_0_2-loc_0_1
     :parameters ()
     :precondition (and (and (clear-loc_0_0 ) (at-loc_0_2 )) (box-loc_0_1 ))
     :effect (and
        (not (at-loc_0_2 ))
        (not (box-loc_0_1 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_1 )
        (box-loc_0_0 )
        (clear-loc_0_2 ))
    )


    (:action push-loc_0_1-loc_0_2
     :parameters ()
     :precondition (and (and (clear-loc_0_3 ) (at-loc_0_1 )) (box-loc_0_2 ))
     :effect (and
        (not (at-loc_0_1 ))
        (not (box-loc_0_2 ))
        (not (clear-loc_0_3 ))
        (at-loc_0_2 )
        (box-loc_0_3 )
        (clear-loc_0_1 ))
    )


    (:action push-loc_0_3-loc_0_2
     :parameters ()
     :precondition (and (and (clear-loc_0_1 ) (at-loc_0_3 )) (box-loc_0_2 ))
     :effect (and
        (not (at-loc_0_3 ))
        (not (box-loc_0_2 ))
        (not (clear-loc_0_1 ))
        (at-loc_0_2 )
        (box-loc_0_1 )
        (clear-loc_0_3 ))
    )


    (:action push-loc_2_1-loc_2_2
     :parameters ()
     :precondition (and (and (clear-loc_2_3 ) (at-loc_2_1 )) (box-loc_2_2 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (box-loc_2_2 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_2 )
        (box-loc_2_3 )
        (clear-loc_2_1 ))
    )


    (:action push-loc_2_3-loc_2_2
     :parameters ()
     :precondition (and (and (clear-loc_2_1 ) (at-loc_2_3 )) (box-loc_2_2 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (box-loc_2_2 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_2 )
        (box-loc_2_1 )
        (clear-loc_2_3 ))
    )


    (:action push-loc_3_1-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_3_1 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_2 )
        (box-loc_3_3 )
        (clear-loc_3_1 ))
    )


    (:action push-loc_3_3-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_3_1 ) (at-loc_3_3 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_2 )
        (box-loc_3_1 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_3_2-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_3_2 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_3 )
        (box-loc_3_4 )
        (clear-loc_3_2 ))
    )


    (:action push-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_3_2 ) (at-loc_3_4 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_3 )
        (box-loc_3_2 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_3_3 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_4 )
        (box-loc_3_5 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_3_5 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_4 )
        (box-loc_3_3 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_3_4-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_3_6 ) (at-loc_3_4 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_5 )
        (box-loc_3_6 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_3_6-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_3_6 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_5 )
        (box-loc_3_4 )
        (clear-loc_3_6 ))
    )


    (:action push-loc_3_5-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_3_7 ) (at-loc_3_5 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_6 )
        (box-loc_3_7 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_3_7-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_3_7 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_6 )
        (box-loc_3_5 )
        (clear-loc_3_7 ))
    )


    (:action push-loc_5_0-loc_5_1
     :parameters ()
     :precondition (and (and (clear-loc_5_2 ) (at-loc_5_0 )) (box-loc_5_1 ))
     :effect (and
        (not (at-loc_5_0 ))
        (not (box-loc_5_1 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_1 )
        (box-loc_5_2 )
        (clear-loc_5_0 ))
    )


    (:action push-loc_5_2-loc_5_1
     :parameters ()
     :precondition (and (and (clear-loc_5_0 ) (at-loc_5_2 )) (box-loc_5_1 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (box-loc_5_1 ))
        (not (clear-loc_5_0 ))
        (at-loc_5_1 )
        (box-loc_5_0 )
        (clear-loc_5_2 ))
    )


    (:action push-loc_5_1-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_5_3 ) (at-loc_5_1 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_2 )
        (box-loc_5_3 )
        (clear-loc_5_1 ))
    )


    (:action push-loc_5_3-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_5_1 ) (at-loc_5_3 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_2 )
        (box-loc_5_1 )
        (clear-loc_5_3 ))
    )


    (:action push-loc_6_0-loc_6_1
     :parameters ()
     :precondition (and (and (clear-loc_6_2 ) (at-loc_6_0 )) (box-loc_6_1 ))
     :effect (and
        (not (at-loc_6_0 ))
        (not (box-loc_6_1 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_1 )
        (box-loc_6_2 )
        (clear-loc_6_0 ))
    )


    (:action push-loc_6_2-loc_6_1
     :parameters ()
     :precondition (and (and (clear-loc_6_0 ) (at-loc_6_2 )) (box-loc_6_1 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (box-loc_6_1 ))
        (not (clear-loc_6_0 ))
        (at-loc_6_1 )
        (box-loc_6_0 )
        (clear-loc_6_2 ))
    )


    (:action push-loc_6_1-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_6_1 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_2 )
        (box-loc_6_3 )
        (clear-loc_6_1 ))
    )


    (:action push-loc_6_3-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_6_1 ) (at-loc_6_3 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_2 )
        (box-loc_6_1 )
        (clear-loc_6_3 ))
    )

)