
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain Sokoban)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (at-loc_0_0 )
        (box-loc_0_0 )
        (clear-loc_0_0 )
        (at-loc_0_6 )
        (box-loc_0_6 )
        (clear-loc_0_6 )
        (at-loc_0_7 )
        (box-loc_0_7 )
        (clear-loc_0_7 )
        (at-loc_0_8 )
        (box-loc_0_8 )
        (clear-loc_0_8 )
        (at-loc_1_0 )
        (box-loc_1_0 )
        (clear-loc_1_0 )
        (at-loc_1_2 )
        (box-loc_1_2 )
        (clear-loc_1_2 )
        (at-loc_1_3 )
        (box-loc_1_3 )
        (clear-loc_1_3 )
        (at-loc_1_4 )
        (box-loc_1_4 )
        (clear-loc_1_4 )
        (at-loc_1_6 )
        (box-loc_1_6 )
        (clear-loc_1_6 )
        (at-loc_1_7 )
        (box-loc_1_7 )
        (clear-loc_1_7 )
        (at-loc_1_8 )
        (box-loc_1_8 )
        (clear-loc_1_8 )
        (at-loc_2_0 )
        (box-loc_2_0 )
        (clear-loc_2_0 )
        (at-loc_2_3 )
        (box-loc_2_3 )
        (clear-loc_2_3 )
        (at-loc_2_4 )
        (box-loc_2_4 )
        (clear-loc_2_4 )
        (at-loc_2_7 )
        (box-loc_2_7 )
        (clear-loc_2_7 )
        (at-loc_2_8 )
        (box-loc_2_8 )
        (clear-loc_2_8 )
        (at-loc_3_3 )
        (box-loc_3_3 )
        (clear-loc_3_3 )
        (at-loc_3_4 )
        (box-loc_3_4 )
        (clear-loc_3_4 )
        (at-loc_3_5 )
        (box-loc_3_5 )
        (clear-loc_3_5 )
        (at-loc_4_1 )
        (box-loc_4_1 )
        (clear-loc_4_1 )
        (at-loc_4_2 )
        (box-loc_4_2 )
        (clear-loc_4_2 )
        (at-loc_4_3 )
        (box-loc_4_3 )
        (clear-loc_4_3 )
        (at-loc_4_4 )
        (box-loc_4_4 )
        (clear-loc_4_4 )
        (at-loc_4_5 )
        (box-loc_4_5 )
        (clear-loc_4_5 )
        (at-loc_4_6 )
        (box-loc_4_6 )
        (clear-loc_4_6 )
        (at-loc_4_7 )
        (box-loc_4_7 )
        (clear-loc_4_7 )
        (at-loc_5_3 )
        (box-loc_5_3 )
        (clear-loc_5_3 )
        (at-loc_5_5 )
        (box-loc_5_5 )
        (clear-loc_5_5 )
        (at-loc_6_0 )
        (box-loc_6_0 )
        (clear-loc_6_0 )
        (at-loc_6_1 )
        (box-loc_6_1 )
        (clear-loc_6_1 )
        (at-loc_6_3 )
        (box-loc_6_3 )
        (clear-loc_6_3 )
        (at-loc_6_4 )
        (box-loc_6_4 )
        (clear-loc_6_4 )
        (at-loc_6_5 )
        (box-loc_6_5 )
        (clear-loc_6_5 )
        (at-loc_6_7 )
        (box-loc_6_7 )
        (clear-loc_6_7 )
        (at-loc_6_8 )
        (box-loc_6_8 )
        (clear-loc_6_8 )
        (at-loc_7_0 )
        (box-loc_7_0 )
        (clear-loc_7_0 )
        (at-loc_7_1 )
        (box-loc_7_1 )
        (clear-loc_7_1 )
        (at-loc_7_7 )
        (box-loc_7_7 )
        (clear-loc_7_7 )
        (at-loc_7_8 )
        (box-loc_7_8 )
        (clear-loc_7_8 )
    )

    (:functions
        
    )

    

    
    (:action move-loc_0_0-loc_1_0
     :parameters ()
     :precondition (and (clear-loc_1_0 ) (at-loc_0_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (clear-loc_1_0 ))
        (at-loc_1_0 )
        (clear-loc_0_0 ))
    )


    (:action move-loc_1_0-loc_0_0
     :parameters ()
     :precondition (and (clear-loc_0_0 ) (at-loc_1_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (clear-loc_0_0 ))
        (at-loc_0_0 )
        (clear-loc_1_0 ))
    )


    (:action move-loc_0_6-loc_1_6
     :parameters ()
     :precondition (and (clear-loc_1_6 ) (at-loc_0_6 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (clear-loc_1_6 ))
        (at-loc_1_6 )
        (clear-loc_0_6 ))
    )


    (:action move-loc_1_6-loc_0_6
     :parameters ()
     :precondition (and (clear-loc_0_6 ) (at-loc_1_6 ))
     :effect (and
        (not (at-loc_1_6 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_6 )
        (clear-loc_1_6 ))
    )


    (:action move-loc_0_7-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_1_7-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_0_8-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_0_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_0_8 ))
    )


    (:action move-loc_1_8-loc_0_8
     :parameters ()
     :precondition (and (clear-loc_0_8 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_8 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_1_0-loc_2_0
     :parameters ()
     :precondition (and (clear-loc_2_0 ) (at-loc_1_0 ))
     :effect (and
        (not (at-loc_1_0 ))
        (not (clear-loc_2_0 ))
        (at-loc_2_0 )
        (clear-loc_1_0 ))
    )


    (:action move-loc_2_0-loc_1_0
     :parameters ()
     :precondition (and (clear-loc_1_0 ) (at-loc_2_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (clear-loc_1_0 ))
        (at-loc_1_0 )
        (clear-loc_2_0 ))
    )


    (:action move-loc_1_3-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_1_3 ))
     :effect (and
        (not (at-loc_1_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_1_3 ))
    )


    (:action move-loc_2_3-loc_1_3
     :parameters ()
     :precondition (and (clear-loc_1_3 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_1_3 ))
        (at-loc_1_3 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_1_4-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_1_4 ))
     :effect (and
        (not (at-loc_1_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_1_4 ))
    )


    (:action move-loc_2_4-loc_1_4
     :parameters ()
     :precondition (and (clear-loc_1_4 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_1_4 ))
        (at-loc_1_4 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_1_7-loc_2_7
     :parameters ()
     :precondition (and (clear-loc_2_7 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_7 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_2_7-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_2_7 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_2_7 ))
    )


    (:action move-loc_1_8-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_2_8-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_2_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_3_3-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_3_4-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_3-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_4_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_3_4-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_3_5-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_4_5-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_4_3-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_5_3-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_4_5-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_5_5-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_5_3-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_5_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_5_3 ))
    )


    (:action move-loc_6_3-loc_5_3
     :parameters ()
     :precondition (and (clear-loc_5_3 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_5_3 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_5_5-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_5_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_5_5 ))
    )


    (:action move-loc_6_5-loc_5_5
     :parameters ()
     :precondition (and (clear-loc_5_5 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_5_5 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_0-loc_7_0
     :parameters ()
     :precondition (and (clear-loc_7_0 ) (at-loc_6_0 ))
     :effect (and
        (not (at-loc_6_0 ))
        (not (clear-loc_7_0 ))
        (at-loc_7_0 )
        (clear-loc_6_0 ))
    )


    (:action move-loc_7_0-loc_6_0
     :parameters ()
     :precondition (and (clear-loc_6_0 ) (at-loc_7_0 ))
     :effect (and
        (not (at-loc_7_0 ))
        (not (clear-loc_6_0 ))
        (at-loc_6_0 )
        (clear-loc_7_0 ))
    )


    (:action move-loc_6_1-loc_7_1
     :parameters ()
     :precondition (and (clear-loc_7_1 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_1 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_7_1-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_7_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_7_1 ))
    )


    (:action move-loc_6_7-loc_7_7
     :parameters ()
     :precondition (and (clear-loc_7_7 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_7 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_7_7-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_7_7 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_7_7 ))
    )


    (:action move-loc_6_8-loc_7_8
     :parameters ()
     :precondition (and (clear-loc_7_8 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_8 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_7_8-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_7_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_7_8 ))
    )


    (:action move-loc_0_6-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_0_6 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_0_6 ))
    )


    (:action move-loc_0_7-loc_0_6
     :parameters ()
     :precondition (and (clear-loc_0_6 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_6 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_0_7-loc_0_8
     :parameters ()
     :precondition (and (clear-loc_0_8 ) (at-loc_0_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_8 )
        (clear-loc_0_7 ))
    )


    (:action move-loc_0_8-loc_0_7
     :parameters ()
     :precondition (and (clear-loc_0_7 ) (at-loc_0_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (clear-loc_0_7 ))
        (at-loc_0_7 )
        (clear-loc_0_8 ))
    )


    (:action move-loc_1_2-loc_1_3
     :parameters ()
     :precondition (and (clear-loc_1_3 ) (at-loc_1_2 ))
     :effect (and
        (not (at-loc_1_2 ))
        (not (clear-loc_1_3 ))
        (at-loc_1_3 )
        (clear-loc_1_2 ))
    )


    (:action move-loc_1_3-loc_1_2
     :parameters ()
     :precondition (and (clear-loc_1_2 ) (at-loc_1_3 ))
     :effect (and
        (not (at-loc_1_3 ))
        (not (clear-loc_1_2 ))
        (at-loc_1_2 )
        (clear-loc_1_3 ))
    )


    (:action move-loc_1_3-loc_1_4
     :parameters ()
     :precondition (and (clear-loc_1_4 ) (at-loc_1_3 ))
     :effect (and
        (not (at-loc_1_3 ))
        (not (clear-loc_1_4 ))
        (at-loc_1_4 )
        (clear-loc_1_3 ))
    )


    (:action move-loc_1_4-loc_1_3
     :parameters ()
     :precondition (and (clear-loc_1_3 ) (at-loc_1_4 ))
     :effect (and
        (not (at-loc_1_4 ))
        (not (clear-loc_1_3 ))
        (at-loc_1_3 )
        (clear-loc_1_4 ))
    )


    (:action move-loc_1_6-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_1_6 ))
     :effect (and
        (not (at-loc_1_6 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_1_6 ))
    )


    (:action move-loc_1_7-loc_1_6
     :parameters ()
     :precondition (and (clear-loc_1_6 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_1_6 ))
        (at-loc_1_6 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_1_7-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_1_7 ))
     :effect (and
        (not (at-loc_1_7 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_1_7 ))
    )


    (:action move-loc_1_8-loc_1_7
     :parameters ()
     :precondition (and (clear-loc_1_7 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_1_7 ))
        (at-loc_1_7 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_2_3-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_2_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_2_3 ))
    )


    (:action move-loc_2_4-loc_2_3
     :parameters ()
     :precondition (and (clear-loc_2_3 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_2_3 ))
        (at-loc_2_3 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_2_7-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_2_7 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_2_7 ))
    )


    (:action move-loc_2_8-loc_2_7
     :parameters ()
     :precondition (and (clear-loc_2_7 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_2_7 ))
        (at-loc_2_7 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_4-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_4_1-loc_4_2
     :parameters ()
     :precondition (and (clear-loc_4_2 ) (at-loc_4_1 ))
     :effect (and
        (not (at-loc_4_1 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_2 )
        (clear-loc_4_1 ))
    )


    (:action move-loc_4_2-loc_4_1
     :parameters ()
     :precondition (and (clear-loc_4_1 ) (at-loc_4_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (clear-loc_4_1 ))
        (at-loc_4_1 )
        (clear-loc_4_2 ))
    )


    (:action move-loc_4_2-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_4_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_4_2 ))
    )


    (:action move-loc_4_3-loc_4_2
     :parameters ()
     :precondition (and (clear-loc_4_2 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_2 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_4_3-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_4_4-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_4_4-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_4_5-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_4_5-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_4_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_4_5 ))
    )


    (:action move-loc_4_6-loc_4_5
     :parameters ()
     :precondition (and (clear-loc_4_5 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_5 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_4_6-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_4_7-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_6_0-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_6_0 ))
     :effect (and
        (not (at-loc_6_0 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_6_0 ))
    )


    (:action move-loc_6_1-loc_6_0
     :parameters ()
     :precondition (and (clear-loc_6_0 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_6_0 ))
        (at-loc_6_0 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_6_4-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_4-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_7-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_6_8-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_7_0-loc_7_1
     :parameters ()
     :precondition (and (clear-loc_7_1 ) (at-loc_7_0 ))
     :effect (and
        (not (at-loc_7_0 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_1 )
        (clear-loc_7_0 ))
    )


    (:action move-loc_7_1-loc_7_0
     :parameters ()
     :precondition (and (clear-loc_7_0 ) (at-loc_7_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (clear-loc_7_0 ))
        (at-loc_7_0 )
        (clear-loc_7_1 ))
    )


    (:action move-loc_7_7-loc_7_8
     :parameters ()
     :precondition (and (clear-loc_7_8 ) (at-loc_7_7 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_8 )
        (clear-loc_7_7 ))
    )


    (:action move-loc_7_8-loc_7_7
     :parameters ()
     :precondition (and (clear-loc_7_7 ) (at-loc_7_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_7 )
        (clear-loc_7_8 ))
    )


    (:action push-loc_0_0-loc_1_0
     :parameters ()
     :precondition (and (and (clear-loc_2_0 ) (at-loc_0_0 )) (box-loc_1_0 ))
     :effect (and
        (not (at-loc_0_0 ))
        (not (box-loc_1_0 ))
        (not (clear-loc_2_0 ))
        (at-loc_1_0 )
        (box-loc_2_0 )
        (clear-loc_0_0 ))
    )


    (:action push-loc_2_0-loc_1_0
     :parameters ()
     :precondition (and (and (clear-loc_0_0 ) (at-loc_2_0 )) (box-loc_1_0 ))
     :effect (and
        (not (at-loc_2_0 ))
        (not (box-loc_1_0 ))
        (not (clear-loc_0_0 ))
        (at-loc_1_0 )
        (box-loc_0_0 )
        (clear-loc_2_0 ))
    )


    (:action push-loc_0_7-loc_1_7
     :parameters ()
     :precondition (and (and (clear-loc_2_7 ) (at-loc_0_7 )) (box-loc_1_7 ))
     :effect (and
        (not (at-loc_0_7 ))
        (not (box-loc_1_7 ))
        (not (clear-loc_2_7 ))
        (at-loc_1_7 )
        (box-loc_2_7 )
        (clear-loc_0_7 ))
    )


    (:action push-loc_2_7-loc_1_7
     :parameters ()
     :precondition (and (and (clear-loc_0_7 ) (at-loc_2_7 )) (box-loc_1_7 ))
     :effect (and
        (not (at-loc_2_7 ))
        (not (box-loc_1_7 ))
        (not (clear-loc_0_7 ))
        (at-loc_1_7 )
        (box-loc_0_7 )
        (clear-loc_2_7 ))
    )


    (:action push-loc_0_8-loc_1_8
     :parameters ()
     :precondition (and (and (clear-loc_2_8 ) (at-loc_0_8 )) (box-loc_1_8 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (box-loc_1_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_1_8 )
        (box-loc_2_8 )
        (clear-loc_0_8 ))
    )


    (:action push-loc_2_8-loc_1_8
     :parameters ()
     :precondition (and (and (clear-loc_0_8 ) (at-loc_2_8 )) (box-loc_1_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (box-loc_1_8 ))
        (not (clear-loc_0_8 ))
        (at-loc_1_8 )
        (box-loc_0_8 )
        (clear-loc_2_8 ))
    )


    (:action push-loc_1_3-loc_2_3
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_1_3 )) (box-loc_2_3 ))
     :effect (and
        (not (at-loc_1_3 ))
        (not (box-loc_2_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_2_3 )
        (box-loc_3_3 )
        (clear-loc_1_3 ))
    )


    (:action push-loc_3_3-loc_2_3
     :parameters ()
     :precondition (and (and (clear-loc_1_3 ) (at-loc_3_3 )) (box-loc_2_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_2_3 ))
        (not (clear-loc_1_3 ))
        (at-loc_2_3 )
        (box-loc_1_3 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_1_4-loc_2_4
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_1_4 )) (box-loc_2_4 ))
     :effect (and
        (not (at-loc_1_4 ))
        (not (box-loc_2_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_2_4 )
        (box-loc_3_4 )
        (clear-loc_1_4 ))
    )


    (:action push-loc_3_4-loc_2_4
     :parameters ()
     :precondition (and (and (clear-loc_1_4 ) (at-loc_3_4 )) (box-loc_2_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_2_4 ))
        (not (clear-loc_1_4 ))
        (at-loc_2_4 )
        (box-loc_1_4 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_2_3-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_2_3 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_2_3 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_3_3 )
        (box-loc_4_3 )
        (clear-loc_2_3 ))
    )


    (:action push-loc_4_3-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_2_3 ) (at-loc_4_3 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_2_3 ))
        (at-loc_3_3 )
        (box-loc_2_3 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_2_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_3_4 )
        (box-loc_4_4 )
        (clear-loc_2_4 ))
    )


    (:action push-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_2_4 ) (at-loc_4_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_3_4 )
        (box-loc_2_4 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_3_3-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_5_3 ) (at-loc_3_3 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_5_3 ))
        (at-loc_4_3 )
        (box-loc_5_3 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_5_3-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_5_3 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_5_3 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_4_3 )
        (box-loc_3_3 )
        (clear-loc_5_3 ))
    )


    (:action push-loc_3_5-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_5_5 ) (at-loc_3_5 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_5_5 ))
        (at-loc_4_5 )
        (box-loc_5_5 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_5_5-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_5_5 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_5_5 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_4_5 )
        (box-loc_3_5 )
        (clear-loc_5_5 ))
    )


    (:action push-loc_4_3-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_4_3 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_5_3 )
        (box-loc_6_3 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_6_3-loc_5_3
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_6_3 )) (box-loc_5_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_5_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_5_3 )
        (box-loc_4_3 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_4_5-loc_5_5
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_4_5 )) (box-loc_5_5 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (box-loc_5_5 ))
        (not (clear-loc_6_5 ))
        (at-loc_5_5 )
        (box-loc_6_5 )
        (clear-loc_4_5 ))
    )


    (:action push-loc_6_5-loc_5_5
     :parameters ()
     :precondition (and (and (clear-loc_4_5 ) (at-loc_6_5 )) (box-loc_5_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_5_5 ))
        (not (clear-loc_4_5 ))
        (at-loc_5_5 )
        (box-loc_4_5 )
        (clear-loc_6_5 ))
    )


    (:action push-loc_0_6-loc_0_7
     :parameters ()
     :precondition (and (and (clear-loc_0_8 ) (at-loc_0_6 )) (box-loc_0_7 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (box-loc_0_7 ))
        (not (clear-loc_0_8 ))
        (at-loc_0_7 )
        (box-loc_0_8 )
        (clear-loc_0_6 ))
    )


    (:action push-loc_0_8-loc_0_7
     :parameters ()
     :precondition (and (and (clear-loc_0_6 ) (at-loc_0_8 )) (box-loc_0_7 ))
     :effect (and
        (not (at-loc_0_8 ))
        (not (box-loc_0_7 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_7 )
        (box-loc_0_6 )
        (clear-loc_0_8 ))
    )


    (:action push-loc_1_2-loc_1_3
     :parameters ()
     :precondition (and (and (clear-loc_1_4 ) (at-loc_1_2 )) (box-loc_1_3 ))
     :effect (and
        (not (at-loc_1_2 ))
        (not (box-loc_1_3 ))
        (not (clear-loc_1_4 ))
        (at-loc_1_3 )
        (box-loc_1_4 )
        (clear-loc_1_2 ))
    )


    (:action push-loc_1_4-loc_1_3
     :parameters ()
     :precondition (and (and (clear-loc_1_2 ) (at-loc_1_4 )) (box-loc_1_3 ))
     :effect (and
        (not (at-loc_1_4 ))
        (not (box-loc_1_3 ))
        (not (clear-loc_1_2 ))
        (at-loc_1_3 )
        (box-loc_1_2 )
        (clear-loc_1_4 ))
    )


    (:action push-loc_1_6-loc_1_7
     :parameters ()
     :precondition (and (and (clear-loc_1_8 ) (at-loc_1_6 )) (box-loc_1_7 ))
     :effect (and
        (not (at-loc_1_6 ))
        (not (box-loc_1_7 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_7 )
        (box-loc_1_8 )
        (clear-loc_1_6 ))
    )


    (:action push-loc_1_8-loc_1_7
     :parameters ()
     :precondition (and (and (clear-loc_1_6 ) (at-loc_1_8 )) (box-loc_1_7 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (box-loc_1_7 ))
        (not (clear-loc_1_6 ))
        (at-loc_1_7 )
        (box-loc_1_6 )
        (clear-loc_1_8 ))
    )


    (:action push-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_3_3 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_4 )
        (box-loc_3_5 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_3_5 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_4 )
        (box-loc_3_3 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_4_1-loc_4_2
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_4_1 )) (box-loc_4_2 ))
     :effect (and
        (not (at-loc_4_1 ))
        (not (box-loc_4_2 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_2 )
        (box-loc_4_3 )
        (clear-loc_4_1 ))
    )


    (:action push-loc_4_3-loc_4_2
     :parameters ()
     :precondition (and (and (clear-loc_4_1 ) (at-loc_4_3 )) (box-loc_4_2 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_4_2 ))
        (not (clear-loc_4_1 ))
        (at-loc_4_2 )
        (box-loc_4_1 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_4_2-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_4_2 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_3 )
        (box-loc_4_4 )
        (clear-loc_4_2 ))
    )


    (:action push-loc_4_4-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_4_2 ) (at-loc_4_4 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_3 )
        (box-loc_4_2 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_4_3-loc_4_4
     :parameters ()
     :precondition (and (and (clear-loc_4_5 ) (at-loc_4_3 )) (box-loc_4_4 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (box-loc_4_4 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_4 )
        (box-loc_4_5 )
        (clear-loc_4_3 ))
    )


    (:action push-loc_4_5-loc_4_4
     :parameters ()
     :precondition (and (and (clear-loc_4_3 ) (at-loc_4_5 )) (box-loc_4_4 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (box-loc_4_4 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_4 )
        (box-loc_4_3 )
        (clear-loc_4_5 ))
    )


    (:action push-loc_4_4-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_4_6 ) (at-loc_4_4 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_5 )
        (box-loc_4_6 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_4_6-loc_4_5
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_4_6 )) (box-loc_4_5 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (box-loc_4_5 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_5 )
        (box-loc_4_4 )
        (clear-loc_4_6 ))
    )


    (:action push-loc_4_5-loc_4_6
     :parameters ()
     :precondition (and (and (clear-loc_4_7 ) (at-loc_4_5 )) (box-loc_4_6 ))
     :effect (and
        (not (at-loc_4_5 ))
        (not (box-loc_4_6 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_6 )
        (box-loc_4_7 )
        (clear-loc_4_5 ))
    )


    (:action push-loc_4_7-loc_4_6
     :parameters ()
     :precondition (and (and (clear-loc_4_5 ) (at-loc_4_7 )) (box-loc_4_6 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (box-loc_4_6 ))
        (not (clear-loc_4_5 ))
        (at-loc_4_6 )
        (box-loc_4_5 )
        (clear-loc_4_7 ))
    )


    (:action push-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_6_3 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_4 )
        (box-loc_6_5 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_6_5 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_4 )
        (box-loc_6_3 )
        (clear-loc_6_5 ))
    )

)