
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Domain file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (domain Sokoban)
    (:requirements :equality)
    (:types
        object
    )

    (:constants
        
    )

    (:predicates
        (at-loc_0_4 )
        (box-loc_0_4 )
        (clear-loc_0_4 )
        (at-loc_0_5 )
        (box-loc_0_5 )
        (clear-loc_0_5 )
        (at-loc_0_6 )
        (box-loc_0_6 )
        (clear-loc_0_6 )
        (at-loc_1_1 )
        (box-loc_1_1 )
        (clear-loc_1_1 )
        (at-loc_1_2 )
        (box-loc_1_2 )
        (clear-loc_1_2 )
        (at-loc_1_8 )
        (box-loc_1_8 )
        (clear-loc_1_8 )
        (at-loc_1_9 )
        (box-loc_1_9 )
        (clear-loc_1_9 )
        (at-loc_2_1 )
        (box-loc_2_1 )
        (clear-loc_2_1 )
        (at-loc_2_2 )
        (box-loc_2_2 )
        (clear-loc_2_2 )
        (at-loc_2_4 )
        (box-loc_2_4 )
        (clear-loc_2_4 )
        (at-loc_2_5 )
        (box-loc_2_5 )
        (clear-loc_2_5 )
        (at-loc_2_6 )
        (box-loc_2_6 )
        (clear-loc_2_6 )
        (at-loc_2_8 )
        (box-loc_2_8 )
        (clear-loc_2_8 )
        (at-loc_2_9 )
        (box-loc_2_9 )
        (clear-loc_2_9 )
        (at-loc_3_1 )
        (box-loc_3_1 )
        (clear-loc_3_1 )
        (at-loc_3_2 )
        (box-loc_3_2 )
        (clear-loc_3_2 )
        (at-loc_3_3 )
        (box-loc_3_3 )
        (clear-loc_3_3 )
        (at-loc_3_4 )
        (box-loc_3_4 )
        (clear-loc_3_4 )
        (at-loc_3_5 )
        (box-loc_3_5 )
        (clear-loc_3_5 )
        (at-loc_3_6 )
        (box-loc_3_6 )
        (clear-loc_3_6 )
        (at-loc_3_7 )
        (box-loc_3_7 )
        (clear-loc_3_7 )
        (at-loc_3_8 )
        (box-loc_3_8 )
        (clear-loc_3_8 )
        (at-loc_3_9 )
        (box-loc_3_9 )
        (clear-loc_3_9 )
        (at-loc_4_2 )
        (box-loc_4_2 )
        (clear-loc_4_2 )
        (at-loc_4_3 )
        (box-loc_4_3 )
        (clear-loc_4_3 )
        (at-loc_4_4 )
        (box-loc_4_4 )
        (clear-loc_4_4 )
        (at-loc_4_6 )
        (box-loc_4_6 )
        (clear-loc_4_6 )
        (at-loc_4_7 )
        (box-loc_4_7 )
        (clear-loc_4_7 )
        (at-loc_4_8 )
        (box-loc_4_8 )
        (clear-loc_4_8 )
        (at-loc_5_1 )
        (box-loc_5_1 )
        (clear-loc_5_1 )
        (at-loc_5_2 )
        (box-loc_5_2 )
        (clear-loc_5_2 )
        (at-loc_5_8 )
        (box-loc_5_8 )
        (clear-loc_5_8 )
        (at-loc_5_9 )
        (box-loc_5_9 )
        (clear-loc_5_9 )
        (at-loc_6_1 )
        (box-loc_6_1 )
        (clear-loc_6_1 )
        (at-loc_6_2 )
        (box-loc_6_2 )
        (clear-loc_6_2 )
        (at-loc_6_3 )
        (box-loc_6_3 )
        (clear-loc_6_3 )
        (at-loc_6_4 )
        (box-loc_6_4 )
        (clear-loc_6_4 )
        (at-loc_6_5 )
        (box-loc_6_5 )
        (clear-loc_6_5 )
        (at-loc_6_6 )
        (box-loc_6_6 )
        (clear-loc_6_6 )
        (at-loc_6_7 )
        (box-loc_6_7 )
        (clear-loc_6_7 )
        (at-loc_6_8 )
        (box-loc_6_8 )
        (clear-loc_6_8 )
        (at-loc_6_9 )
        (box-loc_6_9 )
        (clear-loc_6_9 )
        (at-loc_7_1 )
        (box-loc_7_1 )
        (clear-loc_7_1 )
        (at-loc_7_2 )
        (box-loc_7_2 )
        (clear-loc_7_2 )
        (at-loc_7_3 )
        (box-loc_7_3 )
        (clear-loc_7_3 )
        (at-loc_7_4 )
        (box-loc_7_4 )
        (clear-loc_7_4 )
        (at-loc_7_5 )
        (box-loc_7_5 )
        (clear-loc_7_5 )
        (at-loc_7_6 )
        (box-loc_7_6 )
        (clear-loc_7_6 )
        (at-loc_7_7 )
        (box-loc_7_7 )
        (clear-loc_7_7 )
        (at-loc_7_8 )
        (box-loc_7_8 )
        (clear-loc_7_8 )
        (at-loc_7_9 )
        (box-loc_7_9 )
        (clear-loc_7_9 )
        (at-loc_8_5 )
        (box-loc_8_5 )
        (clear-loc_8_5 )
        (at-loc_9_0 )
        (box-loc_9_0 )
        (clear-loc_9_0 )
        (at-loc_9_1 )
        (box-loc_9_1 )
        (clear-loc_9_1 )
        (at-loc_9_2 )
        (box-loc_9_2 )
        (clear-loc_9_2 )
        (at-loc_9_3 )
        (box-loc_9_3 )
        (clear-loc_9_3 )
        (at-loc_9_5 )
        (box-loc_9_5 )
        (clear-loc_9_5 )
        (at-loc_9_7 )
        (box-loc_9_7 )
        (clear-loc_9_7 )
        (at-loc_9_8 )
        (box-loc_9_8 )
        (clear-loc_9_8 )
        (at-loc_9_9 )
        (box-loc_9_9 )
        (clear-loc_9_9 )
        (at-loc_9_10 )
        (box-loc_9_10 )
        (clear-loc_9_10 )
        (at-loc_10_0 )
        (box-loc_10_0 )
        (clear-loc_10_0 )
        (at-loc_10_1 )
        (box-loc_10_1 )
        (clear-loc_10_1 )
        (at-loc_10_2 )
        (box-loc_10_2 )
        (clear-loc_10_2 )
        (at-loc_10_3 )
        (box-loc_10_3 )
        (clear-loc_10_3 )
        (at-loc_10_7 )
        (box-loc_10_7 )
        (clear-loc_10_7 )
        (at-loc_10_8 )
        (box-loc_10_8 )
        (clear-loc_10_8 )
        (at-loc_10_9 )
        (box-loc_10_9 )
        (clear-loc_10_9 )
        (at-loc_10_10 )
        (box-loc_10_10 )
        (clear-loc_10_10 )
    )

    (:functions
        
    )

    

    
    (:action move-loc_1_1-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_1_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_1_1 ))
    )


    (:action move-loc_2_1-loc_1_1
     :parameters ()
     :precondition (and (clear-loc_1_1 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_1_1 ))
        (at-loc_1_1 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_1_2-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_1_2 ))
     :effect (and
        (not (at-loc_1_2 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_1_2 ))
    )


    (:action move-loc_2_2-loc_1_2
     :parameters ()
     :precondition (and (clear-loc_1_2 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_1_2 ))
        (at-loc_1_2 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_1_8-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_2_8-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_1_9-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_1_9 ))
     :effect (and
        (not (at-loc_1_9 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_1_9 ))
    )


    (:action move-loc_2_9-loc_1_9
     :parameters ()
     :precondition (and (clear-loc_1_9 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_1_9 ))
        (at-loc_1_9 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_2_1-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_3_1-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_2_2-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_3_2-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_3_4-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_2_5-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_3_5-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_2_6-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_2_6 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_2_6 ))
    )


    (:action move-loc_3_6-loc_2_6
     :parameters ()
     :precondition (and (clear-loc_2_6 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_6 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_2_8-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_3_8-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_2_9-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_3_9-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_3_2-loc_4_2
     :parameters ()
     :precondition (and (clear-loc_4_2 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_2 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_4_2-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_4_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_4_2 ))
    )


    (:action move-loc_3_3-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_4_3-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_3_4-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_3_6-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_4_6-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_3_7-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_3_7 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_3_7 ))
    )


    (:action move-loc_4_7-loc_3_7
     :parameters ()
     :precondition (and (clear-loc_3_7 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_7 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_3_8-loc_4_8
     :parameters ()
     :precondition (and (clear-loc_4_8 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_4_8 ))
        (at-loc_4_8 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_4_8-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_4_8 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_4_8 ))
    )


    (:action move-loc_4_2-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_4_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_4_2 ))
    )


    (:action move-loc_5_2-loc_4_2
     :parameters ()
     :precondition (and (clear-loc_4_2 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_2 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_4_8-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_4_8 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_4_8 ))
    )


    (:action move-loc_5_8-loc_4_8
     :parameters ()
     :precondition (and (clear-loc_4_8 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_4_8 ))
        (at-loc_4_8 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_5_1-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_6_1-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_5_2-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_6_2-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_5_8-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_6_8-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_5_9-loc_6_9
     :parameters ()
     :precondition (and (clear-loc_6_9 ) (at-loc_5_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_9 )
        (clear-loc_5_9 ))
    )


    (:action move-loc_6_9-loc_5_9
     :parameters ()
     :precondition (and (clear-loc_5_9 ) (at-loc_6_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_9 )
        (clear-loc_6_9 ))
    )


    (:action move-loc_6_1-loc_7_1
     :parameters ()
     :precondition (and (clear-loc_7_1 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_1 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_7_1-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_7_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_7_1 ))
    )


    (:action move-loc_6_2-loc_7_2
     :parameters ()
     :precondition (and (clear-loc_7_2 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_7_2 ))
        (at-loc_7_2 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_7_2-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_7_2 ))
     :effect (and
        (not (at-loc_7_2 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_7_2 ))
    )


    (:action move-loc_6_3-loc_7_3
     :parameters ()
     :precondition (and (clear-loc_7_3 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_7_3 ))
        (at-loc_7_3 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_7_3-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_7_3 ))
     :effect (and
        (not (at-loc_7_3 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_7_3 ))
    )


    (:action move-loc_6_4-loc_7_4
     :parameters ()
     :precondition (and (clear-loc_7_4 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_7_4 ))
        (at-loc_7_4 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_7_4-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_7_4 ))
     :effect (and
        (not (at-loc_7_4 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_7_4 ))
    )


    (:action move-loc_6_5-loc_7_5
     :parameters ()
     :precondition (and (clear-loc_7_5 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_5 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_7_5-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_7_5 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_7_5 ))
    )


    (:action move-loc_6_6-loc_7_6
     :parameters ()
     :precondition (and (clear-loc_7_6 ) (at-loc_6_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (clear-loc_7_6 ))
        (at-loc_7_6 )
        (clear-loc_6_6 ))
    )


    (:action move-loc_7_6-loc_6_6
     :parameters ()
     :precondition (and (clear-loc_6_6 ) (at-loc_7_6 ))
     :effect (and
        (not (at-loc_7_6 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_6 )
        (clear-loc_7_6 ))
    )


    (:action move-loc_6_7-loc_7_7
     :parameters ()
     :precondition (and (clear-loc_7_7 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_7 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_7_7-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_7_7 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_7_7 ))
    )


    (:action move-loc_6_8-loc_7_8
     :parameters ()
     :precondition (and (clear-loc_7_8 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_8 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_7_8-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_7_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_7_8 ))
    )


    (:action move-loc_6_9-loc_7_9
     :parameters ()
     :precondition (and (clear-loc_7_9 ) (at-loc_6_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (clear-loc_7_9 ))
        (at-loc_7_9 )
        (clear-loc_6_9 ))
    )


    (:action move-loc_7_9-loc_6_9
     :parameters ()
     :precondition (and (clear-loc_6_9 ) (at-loc_7_9 ))
     :effect (and
        (not (at-loc_7_9 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_9 )
        (clear-loc_7_9 ))
    )


    (:action move-loc_7_5-loc_8_5
     :parameters ()
     :precondition (and (clear-loc_8_5 ) (at-loc_7_5 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (clear-loc_8_5 ))
        (at-loc_8_5 )
        (clear-loc_7_5 ))
    )


    (:action move-loc_8_5-loc_7_5
     :parameters ()
     :precondition (and (clear-loc_7_5 ) (at-loc_8_5 ))
     :effect (and
        (not (at-loc_8_5 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_5 )
        (clear-loc_8_5 ))
    )


    (:action move-loc_8_5-loc_9_5
     :parameters ()
     :precondition (and (clear-loc_9_5 ) (at-loc_8_5 ))
     :effect (and
        (not (at-loc_8_5 ))
        (not (clear-loc_9_5 ))
        (at-loc_9_5 )
        (clear-loc_8_5 ))
    )


    (:action move-loc_9_5-loc_8_5
     :parameters ()
     :precondition (and (clear-loc_8_5 ) (at-loc_9_5 ))
     :effect (and
        (not (at-loc_9_5 ))
        (not (clear-loc_8_5 ))
        (at-loc_8_5 )
        (clear-loc_9_5 ))
    )


    (:action move-loc_9_0-loc_10_0
     :parameters ()
     :precondition (and (clear-loc_10_0 ) (at-loc_9_0 ))
     :effect (and
        (not (at-loc_9_0 ))
        (not (clear-loc_10_0 ))
        (at-loc_10_0 )
        (clear-loc_9_0 ))
    )


    (:action move-loc_10_0-loc_9_0
     :parameters ()
     :precondition (and (clear-loc_9_0 ) (at-loc_10_0 ))
     :effect (and
        (not (at-loc_10_0 ))
        (not (clear-loc_9_0 ))
        (at-loc_9_0 )
        (clear-loc_10_0 ))
    )


    (:action move-loc_9_1-loc_10_1
     :parameters ()
     :precondition (and (clear-loc_10_1 ) (at-loc_9_1 ))
     :effect (and
        (not (at-loc_9_1 ))
        (not (clear-loc_10_1 ))
        (at-loc_10_1 )
        (clear-loc_9_1 ))
    )


    (:action move-loc_10_1-loc_9_1
     :parameters ()
     :precondition (and (clear-loc_9_1 ) (at-loc_10_1 ))
     :effect (and
        (not (at-loc_10_1 ))
        (not (clear-loc_9_1 ))
        (at-loc_9_1 )
        (clear-loc_10_1 ))
    )


    (:action move-loc_9_2-loc_10_2
     :parameters ()
     :precondition (and (clear-loc_10_2 ) (at-loc_9_2 ))
     :effect (and
        (not (at-loc_9_2 ))
        (not (clear-loc_10_2 ))
        (at-loc_10_2 )
        (clear-loc_9_2 ))
    )


    (:action move-loc_10_2-loc_9_2
     :parameters ()
     :precondition (and (clear-loc_9_2 ) (at-loc_10_2 ))
     :effect (and
        (not (at-loc_10_2 ))
        (not (clear-loc_9_2 ))
        (at-loc_9_2 )
        (clear-loc_10_2 ))
    )


    (:action move-loc_9_3-loc_10_3
     :parameters ()
     :precondition (and (clear-loc_10_3 ) (at-loc_9_3 ))
     :effect (and
        (not (at-loc_9_3 ))
        (not (clear-loc_10_3 ))
        (at-loc_10_3 )
        (clear-loc_9_3 ))
    )


    (:action move-loc_10_3-loc_9_3
     :parameters ()
     :precondition (and (clear-loc_9_3 ) (at-loc_10_3 ))
     :effect (and
        (not (at-loc_10_3 ))
        (not (clear-loc_9_3 ))
        (at-loc_9_3 )
        (clear-loc_10_3 ))
    )


    (:action move-loc_9_7-loc_10_7
     :parameters ()
     :precondition (and (clear-loc_10_7 ) (at-loc_9_7 ))
     :effect (and
        (not (at-loc_9_7 ))
        (not (clear-loc_10_7 ))
        (at-loc_10_7 )
        (clear-loc_9_7 ))
    )


    (:action move-loc_10_7-loc_9_7
     :parameters ()
     :precondition (and (clear-loc_9_7 ) (at-loc_10_7 ))
     :effect (and
        (not (at-loc_10_7 ))
        (not (clear-loc_9_7 ))
        (at-loc_9_7 )
        (clear-loc_10_7 ))
    )


    (:action move-loc_9_8-loc_10_8
     :parameters ()
     :precondition (and (clear-loc_10_8 ) (at-loc_9_8 ))
     :effect (and
        (not (at-loc_9_8 ))
        (not (clear-loc_10_8 ))
        (at-loc_10_8 )
        (clear-loc_9_8 ))
    )


    (:action move-loc_10_8-loc_9_8
     :parameters ()
     :precondition (and (clear-loc_9_8 ) (at-loc_10_8 ))
     :effect (and
        (not (at-loc_10_8 ))
        (not (clear-loc_9_8 ))
        (at-loc_9_8 )
        (clear-loc_10_8 ))
    )


    (:action move-loc_9_9-loc_10_9
     :parameters ()
     :precondition (and (clear-loc_10_9 ) (at-loc_9_9 ))
     :effect (and
        (not (at-loc_9_9 ))
        (not (clear-loc_10_9 ))
        (at-loc_10_9 )
        (clear-loc_9_9 ))
    )


    (:action move-loc_10_9-loc_9_9
     :parameters ()
     :precondition (and (clear-loc_9_9 ) (at-loc_10_9 ))
     :effect (and
        (not (at-loc_10_9 ))
        (not (clear-loc_9_9 ))
        (at-loc_9_9 )
        (clear-loc_10_9 ))
    )


    (:action move-loc_9_10-loc_10_10
     :parameters ()
     :precondition (and (clear-loc_10_10 ) (at-loc_9_10 ))
     :effect (and
        (not (at-loc_9_10 ))
        (not (clear-loc_10_10 ))
        (at-loc_10_10 )
        (clear-loc_9_10 ))
    )


    (:action move-loc_10_10-loc_9_10
     :parameters ()
     :precondition (and (clear-loc_9_10 ) (at-loc_10_10 ))
     :effect (and
        (not (at-loc_10_10 ))
        (not (clear-loc_9_10 ))
        (at-loc_9_10 )
        (clear-loc_10_10 ))
    )


    (:action move-loc_0_4-loc_0_5
     :parameters ()
     :precondition (and (clear-loc_0_5 ) (at-loc_0_4 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_5 )
        (clear-loc_0_4 ))
    )


    (:action move-loc_0_5-loc_0_4
     :parameters ()
     :precondition (and (clear-loc_0_4 ) (at-loc_0_5 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_4 )
        (clear-loc_0_5 ))
    )


    (:action move-loc_0_5-loc_0_6
     :parameters ()
     :precondition (and (clear-loc_0_6 ) (at-loc_0_5 ))
     :effect (and
        (not (at-loc_0_5 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_6 )
        (clear-loc_0_5 ))
    )


    (:action move-loc_0_6-loc_0_5
     :parameters ()
     :precondition (and (clear-loc_0_5 ) (at-loc_0_6 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (clear-loc_0_5 ))
        (at-loc_0_5 )
        (clear-loc_0_6 ))
    )


    (:action move-loc_1_1-loc_1_2
     :parameters ()
     :precondition (and (clear-loc_1_2 ) (at-loc_1_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (clear-loc_1_2 ))
        (at-loc_1_2 )
        (clear-loc_1_1 ))
    )


    (:action move-loc_1_2-loc_1_1
     :parameters ()
     :precondition (and (clear-loc_1_1 ) (at-loc_1_2 ))
     :effect (and
        (not (at-loc_1_2 ))
        (not (clear-loc_1_1 ))
        (at-loc_1_1 )
        (clear-loc_1_2 ))
    )


    (:action move-loc_1_8-loc_1_9
     :parameters ()
     :precondition (and (clear-loc_1_9 ) (at-loc_1_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (clear-loc_1_9 ))
        (at-loc_1_9 )
        (clear-loc_1_8 ))
    )


    (:action move-loc_1_9-loc_1_8
     :parameters ()
     :precondition (and (clear-loc_1_8 ) (at-loc_1_9 ))
     :effect (and
        (not (at-loc_1_9 ))
        (not (clear-loc_1_8 ))
        (at-loc_1_8 )
        (clear-loc_1_9 ))
    )


    (:action move-loc_2_1-loc_2_2
     :parameters ()
     :precondition (and (clear-loc_2_2 ) (at-loc_2_1 ))
     :effect (and
        (not (at-loc_2_1 ))
        (not (clear-loc_2_2 ))
        (at-loc_2_2 )
        (clear-loc_2_1 ))
    )


    (:action move-loc_2_2-loc_2_1
     :parameters ()
     :precondition (and (clear-loc_2_1 ) (at-loc_2_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (clear-loc_2_1 ))
        (at-loc_2_1 )
        (clear-loc_2_2 ))
    )


    (:action move-loc_2_4-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_2_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_2_4 ))
    )


    (:action move-loc_2_5-loc_2_4
     :parameters ()
     :precondition (and (clear-loc_2_4 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_4 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_2_5-loc_2_6
     :parameters ()
     :precondition (and (clear-loc_2_6 ) (at-loc_2_5 ))
     :effect (and
        (not (at-loc_2_5 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_6 )
        (clear-loc_2_5 ))
    )


    (:action move-loc_2_6-loc_2_5
     :parameters ()
     :precondition (and (clear-loc_2_5 ) (at-loc_2_6 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (clear-loc_2_5 ))
        (at-loc_2_5 )
        (clear-loc_2_6 ))
    )


    (:action move-loc_2_8-loc_2_9
     :parameters ()
     :precondition (and (clear-loc_2_9 ) (at-loc_2_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (clear-loc_2_9 ))
        (at-loc_2_9 )
        (clear-loc_2_8 ))
    )


    (:action move-loc_2_9-loc_2_8
     :parameters ()
     :precondition (and (clear-loc_2_8 ) (at-loc_2_9 ))
     :effect (and
        (not (at-loc_2_9 ))
        (not (clear-loc_2_8 ))
        (at-loc_2_8 )
        (clear-loc_2_9 ))
    )


    (:action move-loc_3_1-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_3_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_3_1 ))
    )


    (:action move-loc_3_2-loc_3_1
     :parameters ()
     :precondition (and (clear-loc_3_1 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_1 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_3_2-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_2 ))
    )


    (:action move-loc_3_3-loc_3_2
     :parameters ()
     :precondition (and (clear-loc_3_2 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_2 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_3 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_3 ))
    )


    (:action move-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (clear-loc_3_3 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_3 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_4-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_3_4 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_3_4 ))
    )


    (:action move-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (clear-loc_3_4 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_4 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_3_5-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_3_5 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_3_5 ))
    )


    (:action move-loc_3_6-loc_3_5
     :parameters ()
     :precondition (and (clear-loc_3_5 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_5 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_3_6-loc_3_7
     :parameters ()
     :precondition (and (clear-loc_3_7 ) (at-loc_3_6 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_7 )
        (clear-loc_3_6 ))
    )


    (:action move-loc_3_7-loc_3_6
     :parameters ()
     :precondition (and (clear-loc_3_6 ) (at-loc_3_7 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_6 )
        (clear-loc_3_7 ))
    )


    (:action move-loc_3_7-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_3_7 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_3_7 ))
    )


    (:action move-loc_3_8-loc_3_7
     :parameters ()
     :precondition (and (clear-loc_3_7 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_7 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_3_8-loc_3_9
     :parameters ()
     :precondition (and (clear-loc_3_9 ) (at-loc_3_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_9 )
        (clear-loc_3_8 ))
    )


    (:action move-loc_3_9-loc_3_8
     :parameters ()
     :precondition (and (clear-loc_3_8 ) (at-loc_3_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_8 )
        (clear-loc_3_9 ))
    )


    (:action move-loc_4_2-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_4_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_4_2 ))
    )


    (:action move-loc_4_3-loc_4_2
     :parameters ()
     :precondition (and (clear-loc_4_2 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_2 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_4_3-loc_4_4
     :parameters ()
     :precondition (and (clear-loc_4_4 ) (at-loc_4_3 ))
     :effect (and
        (not (at-loc_4_3 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_4 )
        (clear-loc_4_3 ))
    )


    (:action move-loc_4_4-loc_4_3
     :parameters ()
     :precondition (and (clear-loc_4_3 ) (at-loc_4_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (clear-loc_4_3 ))
        (at-loc_4_3 )
        (clear-loc_4_4 ))
    )


    (:action move-loc_4_6-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_4_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_4_6 ))
    )


    (:action move-loc_4_7-loc_4_6
     :parameters ()
     :precondition (and (clear-loc_4_6 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_6 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_4_7-loc_4_8
     :parameters ()
     :precondition (and (clear-loc_4_8 ) (at-loc_4_7 ))
     :effect (and
        (not (at-loc_4_7 ))
        (not (clear-loc_4_8 ))
        (at-loc_4_8 )
        (clear-loc_4_7 ))
    )


    (:action move-loc_4_8-loc_4_7
     :parameters ()
     :precondition (and (clear-loc_4_7 ) (at-loc_4_8 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (clear-loc_4_7 ))
        (at-loc_4_7 )
        (clear-loc_4_8 ))
    )


    (:action move-loc_5_1-loc_5_2
     :parameters ()
     :precondition (and (clear-loc_5_2 ) (at-loc_5_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (clear-loc_5_2 ))
        (at-loc_5_2 )
        (clear-loc_5_1 ))
    )


    (:action move-loc_5_2-loc_5_1
     :parameters ()
     :precondition (and (clear-loc_5_1 ) (at-loc_5_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (clear-loc_5_1 ))
        (at-loc_5_1 )
        (clear-loc_5_2 ))
    )


    (:action move-loc_5_8-loc_5_9
     :parameters ()
     :precondition (and (clear-loc_5_9 ) (at-loc_5_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (clear-loc_5_9 ))
        (at-loc_5_9 )
        (clear-loc_5_8 ))
    )


    (:action move-loc_5_9-loc_5_8
     :parameters ()
     :precondition (and (clear-loc_5_8 ) (at-loc_5_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (clear-loc_5_8 ))
        (at-loc_5_8 )
        (clear-loc_5_9 ))
    )


    (:action move-loc_6_1-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_6_1 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_6_1 ))
    )


    (:action move-loc_6_2-loc_6_1
     :parameters ()
     :precondition (and (clear-loc_6_1 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_1 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_6_2-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_6_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_6_2 ))
    )


    (:action move-loc_6_3-loc_6_2
     :parameters ()
     :precondition (and (clear-loc_6_2 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_2 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_3 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_3 ))
    )


    (:action move-loc_6_4-loc_6_3
     :parameters ()
     :precondition (and (clear-loc_6_3 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_3 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_4-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_6_4 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_6_4 ))
    )


    (:action move-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (clear-loc_6_4 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_4 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_5-loc_6_6
     :parameters ()
     :precondition (and (clear-loc_6_6 ) (at-loc_6_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_6 )
        (clear-loc_6_5 ))
    )


    (:action move-loc_6_6-loc_6_5
     :parameters ()
     :precondition (and (clear-loc_6_5 ) (at-loc_6_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_5 )
        (clear-loc_6_6 ))
    )


    (:action move-loc_6_6-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_6_6 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_6_6 ))
    )


    (:action move-loc_6_7-loc_6_6
     :parameters ()
     :precondition (and (clear-loc_6_6 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_6 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_6_7-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_6_7 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_6_7 ))
    )


    (:action move-loc_6_8-loc_6_7
     :parameters ()
     :precondition (and (clear-loc_6_7 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_7 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_6_8-loc_6_9
     :parameters ()
     :precondition (and (clear-loc_6_9 ) (at-loc_6_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_9 )
        (clear-loc_6_8 ))
    )


    (:action move-loc_6_9-loc_6_8
     :parameters ()
     :precondition (and (clear-loc_6_8 ) (at-loc_6_9 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_8 )
        (clear-loc_6_9 ))
    )


    (:action move-loc_7_1-loc_7_2
     :parameters ()
     :precondition (and (clear-loc_7_2 ) (at-loc_7_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (clear-loc_7_2 ))
        (at-loc_7_2 )
        (clear-loc_7_1 ))
    )


    (:action move-loc_7_2-loc_7_1
     :parameters ()
     :precondition (and (clear-loc_7_1 ) (at-loc_7_2 ))
     :effect (and
        (not (at-loc_7_2 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_1 )
        (clear-loc_7_2 ))
    )


    (:action move-loc_7_2-loc_7_3
     :parameters ()
     :precondition (and (clear-loc_7_3 ) (at-loc_7_2 ))
     :effect (and
        (not (at-loc_7_2 ))
        (not (clear-loc_7_3 ))
        (at-loc_7_3 )
        (clear-loc_7_2 ))
    )


    (:action move-loc_7_3-loc_7_2
     :parameters ()
     :precondition (and (clear-loc_7_2 ) (at-loc_7_3 ))
     :effect (and
        (not (at-loc_7_3 ))
        (not (clear-loc_7_2 ))
        (at-loc_7_2 )
        (clear-loc_7_3 ))
    )


    (:action move-loc_7_3-loc_7_4
     :parameters ()
     :precondition (and (clear-loc_7_4 ) (at-loc_7_3 ))
     :effect (and
        (not (at-loc_7_3 ))
        (not (clear-loc_7_4 ))
        (at-loc_7_4 )
        (clear-loc_7_3 ))
    )


    (:action move-loc_7_4-loc_7_3
     :parameters ()
     :precondition (and (clear-loc_7_3 ) (at-loc_7_4 ))
     :effect (and
        (not (at-loc_7_4 ))
        (not (clear-loc_7_3 ))
        (at-loc_7_3 )
        (clear-loc_7_4 ))
    )


    (:action move-loc_7_4-loc_7_5
     :parameters ()
     :precondition (and (clear-loc_7_5 ) (at-loc_7_4 ))
     :effect (and
        (not (at-loc_7_4 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_5 )
        (clear-loc_7_4 ))
    )


    (:action move-loc_7_5-loc_7_4
     :parameters ()
     :precondition (and (clear-loc_7_4 ) (at-loc_7_5 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (clear-loc_7_4 ))
        (at-loc_7_4 )
        (clear-loc_7_5 ))
    )


    (:action move-loc_7_5-loc_7_6
     :parameters ()
     :precondition (and (clear-loc_7_6 ) (at-loc_7_5 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (clear-loc_7_6 ))
        (at-loc_7_6 )
        (clear-loc_7_5 ))
    )


    (:action move-loc_7_6-loc_7_5
     :parameters ()
     :precondition (and (clear-loc_7_5 ) (at-loc_7_6 ))
     :effect (and
        (not (at-loc_7_6 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_5 )
        (clear-loc_7_6 ))
    )


    (:action move-loc_7_6-loc_7_7
     :parameters ()
     :precondition (and (clear-loc_7_7 ) (at-loc_7_6 ))
     :effect (and
        (not (at-loc_7_6 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_7 )
        (clear-loc_7_6 ))
    )


    (:action move-loc_7_7-loc_7_6
     :parameters ()
     :precondition (and (clear-loc_7_6 ) (at-loc_7_7 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (clear-loc_7_6 ))
        (at-loc_7_6 )
        (clear-loc_7_7 ))
    )


    (:action move-loc_7_7-loc_7_8
     :parameters ()
     :precondition (and (clear-loc_7_8 ) (at-loc_7_7 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_8 )
        (clear-loc_7_7 ))
    )


    (:action move-loc_7_8-loc_7_7
     :parameters ()
     :precondition (and (clear-loc_7_7 ) (at-loc_7_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_7 )
        (clear-loc_7_8 ))
    )


    (:action move-loc_7_8-loc_7_9
     :parameters ()
     :precondition (and (clear-loc_7_9 ) (at-loc_7_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (clear-loc_7_9 ))
        (at-loc_7_9 )
        (clear-loc_7_8 ))
    )


    (:action move-loc_7_9-loc_7_8
     :parameters ()
     :precondition (and (clear-loc_7_8 ) (at-loc_7_9 ))
     :effect (and
        (not (at-loc_7_9 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_8 )
        (clear-loc_7_9 ))
    )


    (:action move-loc_9_0-loc_9_1
     :parameters ()
     :precondition (and (clear-loc_9_1 ) (at-loc_9_0 ))
     :effect (and
        (not (at-loc_9_0 ))
        (not (clear-loc_9_1 ))
        (at-loc_9_1 )
        (clear-loc_9_0 ))
    )


    (:action move-loc_9_1-loc_9_0
     :parameters ()
     :precondition (and (clear-loc_9_0 ) (at-loc_9_1 ))
     :effect (and
        (not (at-loc_9_1 ))
        (not (clear-loc_9_0 ))
        (at-loc_9_0 )
        (clear-loc_9_1 ))
    )


    (:action move-loc_9_1-loc_9_2
     :parameters ()
     :precondition (and (clear-loc_9_2 ) (at-loc_9_1 ))
     :effect (and
        (not (at-loc_9_1 ))
        (not (clear-loc_9_2 ))
        (at-loc_9_2 )
        (clear-loc_9_1 ))
    )


    (:action move-loc_9_2-loc_9_1
     :parameters ()
     :precondition (and (clear-loc_9_1 ) (at-loc_9_2 ))
     :effect (and
        (not (at-loc_9_2 ))
        (not (clear-loc_9_1 ))
        (at-loc_9_1 )
        (clear-loc_9_2 ))
    )


    (:action move-loc_9_2-loc_9_3
     :parameters ()
     :precondition (and (clear-loc_9_3 ) (at-loc_9_2 ))
     :effect (and
        (not (at-loc_9_2 ))
        (not (clear-loc_9_3 ))
        (at-loc_9_3 )
        (clear-loc_9_2 ))
    )


    (:action move-loc_9_3-loc_9_2
     :parameters ()
     :precondition (and (clear-loc_9_2 ) (at-loc_9_3 ))
     :effect (and
        (not (at-loc_9_3 ))
        (not (clear-loc_9_2 ))
        (at-loc_9_2 )
        (clear-loc_9_3 ))
    )


    (:action move-loc_9_7-loc_9_8
     :parameters ()
     :precondition (and (clear-loc_9_8 ) (at-loc_9_7 ))
     :effect (and
        (not (at-loc_9_7 ))
        (not (clear-loc_9_8 ))
        (at-loc_9_8 )
        (clear-loc_9_7 ))
    )


    (:action move-loc_9_8-loc_9_7
     :parameters ()
     :precondition (and (clear-loc_9_7 ) (at-loc_9_8 ))
     :effect (and
        (not (at-loc_9_8 ))
        (not (clear-loc_9_7 ))
        (at-loc_9_7 )
        (clear-loc_9_8 ))
    )


    (:action move-loc_9_8-loc_9_9
     :parameters ()
     :precondition (and (clear-loc_9_9 ) (at-loc_9_8 ))
     :effect (and
        (not (at-loc_9_8 ))
        (not (clear-loc_9_9 ))
        (at-loc_9_9 )
        (clear-loc_9_8 ))
    )


    (:action move-loc_9_9-loc_9_8
     :parameters ()
     :precondition (and (clear-loc_9_8 ) (at-loc_9_9 ))
     :effect (and
        (not (at-loc_9_9 ))
        (not (clear-loc_9_8 ))
        (at-loc_9_8 )
        (clear-loc_9_9 ))
    )


    (:action move-loc_9_9-loc_9_10
     :parameters ()
     :precondition (and (clear-loc_9_10 ) (at-loc_9_9 ))
     :effect (and
        (not (at-loc_9_9 ))
        (not (clear-loc_9_10 ))
        (at-loc_9_10 )
        (clear-loc_9_9 ))
    )


    (:action move-loc_9_10-loc_9_9
     :parameters ()
     :precondition (and (clear-loc_9_9 ) (at-loc_9_10 ))
     :effect (and
        (not (at-loc_9_10 ))
        (not (clear-loc_9_9 ))
        (at-loc_9_9 )
        (clear-loc_9_10 ))
    )


    (:action move-loc_10_0-loc_10_1
     :parameters ()
     :precondition (and (clear-loc_10_1 ) (at-loc_10_0 ))
     :effect (and
        (not (at-loc_10_0 ))
        (not (clear-loc_10_1 ))
        (at-loc_10_1 )
        (clear-loc_10_0 ))
    )


    (:action move-loc_10_1-loc_10_0
     :parameters ()
     :precondition (and (clear-loc_10_0 ) (at-loc_10_1 ))
     :effect (and
        (not (at-loc_10_1 ))
        (not (clear-loc_10_0 ))
        (at-loc_10_0 )
        (clear-loc_10_1 ))
    )


    (:action move-loc_10_1-loc_10_2
     :parameters ()
     :precondition (and (clear-loc_10_2 ) (at-loc_10_1 ))
     :effect (and
        (not (at-loc_10_1 ))
        (not (clear-loc_10_2 ))
        (at-loc_10_2 )
        (clear-loc_10_1 ))
    )


    (:action move-loc_10_2-loc_10_1
     :parameters ()
     :precondition (and (clear-loc_10_1 ) (at-loc_10_2 ))
     :effect (and
        (not (at-loc_10_2 ))
        (not (clear-loc_10_1 ))
        (at-loc_10_1 )
        (clear-loc_10_2 ))
    )


    (:action move-loc_10_2-loc_10_3
     :parameters ()
     :precondition (and (clear-loc_10_3 ) (at-loc_10_2 ))
     :effect (and
        (not (at-loc_10_2 ))
        (not (clear-loc_10_3 ))
        (at-loc_10_3 )
        (clear-loc_10_2 ))
    )


    (:action move-loc_10_3-loc_10_2
     :parameters ()
     :precondition (and (clear-loc_10_2 ) (at-loc_10_3 ))
     :effect (and
        (not (at-loc_10_3 ))
        (not (clear-loc_10_2 ))
        (at-loc_10_2 )
        (clear-loc_10_3 ))
    )


    (:action move-loc_10_7-loc_10_8
     :parameters ()
     :precondition (and (clear-loc_10_8 ) (at-loc_10_7 ))
     :effect (and
        (not (at-loc_10_7 ))
        (not (clear-loc_10_8 ))
        (at-loc_10_8 )
        (clear-loc_10_7 ))
    )


    (:action move-loc_10_8-loc_10_7
     :parameters ()
     :precondition (and (clear-loc_10_7 ) (at-loc_10_8 ))
     :effect (and
        (not (at-loc_10_8 ))
        (not (clear-loc_10_7 ))
        (at-loc_10_7 )
        (clear-loc_10_8 ))
    )


    (:action move-loc_10_8-loc_10_9
     :parameters ()
     :precondition (and (clear-loc_10_9 ) (at-loc_10_8 ))
     :effect (and
        (not (at-loc_10_8 ))
        (not (clear-loc_10_9 ))
        (at-loc_10_9 )
        (clear-loc_10_8 ))
    )


    (:action move-loc_10_9-loc_10_8
     :parameters ()
     :precondition (and (clear-loc_10_8 ) (at-loc_10_9 ))
     :effect (and
        (not (at-loc_10_9 ))
        (not (clear-loc_10_8 ))
        (at-loc_10_8 )
        (clear-loc_10_9 ))
    )


    (:action move-loc_10_9-loc_10_10
     :parameters ()
     :precondition (and (clear-loc_10_10 ) (at-loc_10_9 ))
     :effect (and
        (not (at-loc_10_9 ))
        (not (clear-loc_10_10 ))
        (at-loc_10_10 )
        (clear-loc_10_9 ))
    )


    (:action move-loc_10_10-loc_10_9
     :parameters ()
     :precondition (and (clear-loc_10_9 ) (at-loc_10_10 ))
     :effect (and
        (not (at-loc_10_10 ))
        (not (clear-loc_10_9 ))
        (at-loc_10_9 )
        (clear-loc_10_10 ))
    )


    (:action push-loc_1_1-loc_2_1
     :parameters ()
     :precondition (and (and (clear-loc_3_1 ) (at-loc_1_1 )) (box-loc_2_1 ))
     :effect (and
        (not (at-loc_1_1 ))
        (not (box-loc_2_1 ))
        (not (clear-loc_3_1 ))
        (at-loc_2_1 )
        (box-loc_3_1 )
        (clear-loc_1_1 ))
    )


    (:action push-loc_3_1-loc_2_1
     :parameters ()
     :precondition (and (and (clear-loc_1_1 ) (at-loc_3_1 )) (box-loc_2_1 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (box-loc_2_1 ))
        (not (clear-loc_1_1 ))
        (at-loc_2_1 )
        (box-loc_1_1 )
        (clear-loc_3_1 ))
    )


    (:action push-loc_1_2-loc_2_2
     :parameters ()
     :precondition (and (and (clear-loc_3_2 ) (at-loc_1_2 )) (box-loc_2_2 ))
     :effect (and
        (not (at-loc_1_2 ))
        (not (box-loc_2_2 ))
        (not (clear-loc_3_2 ))
        (at-loc_2_2 )
        (box-loc_3_2 )
        (clear-loc_1_2 ))
    )


    (:action push-loc_3_2-loc_2_2
     :parameters ()
     :precondition (and (and (clear-loc_1_2 ) (at-loc_3_2 )) (box-loc_2_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (box-loc_2_2 ))
        (not (clear-loc_1_2 ))
        (at-loc_2_2 )
        (box-loc_1_2 )
        (clear-loc_3_2 ))
    )


    (:action push-loc_1_8-loc_2_8
     :parameters ()
     :precondition (and (and (clear-loc_3_8 ) (at-loc_1_8 )) (box-loc_2_8 ))
     :effect (and
        (not (at-loc_1_8 ))
        (not (box-loc_2_8 ))
        (not (clear-loc_3_8 ))
        (at-loc_2_8 )
        (box-loc_3_8 )
        (clear-loc_1_8 ))
    )


    (:action push-loc_3_8-loc_2_8
     :parameters ()
     :precondition (and (and (clear-loc_1_8 ) (at-loc_3_8 )) (box-loc_2_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (box-loc_2_8 ))
        (not (clear-loc_1_8 ))
        (at-loc_2_8 )
        (box-loc_1_8 )
        (clear-loc_3_8 ))
    )


    (:action push-loc_1_9-loc_2_9
     :parameters ()
     :precondition (and (and (clear-loc_3_9 ) (at-loc_1_9 )) (box-loc_2_9 ))
     :effect (and
        (not (at-loc_1_9 ))
        (not (box-loc_2_9 ))
        (not (clear-loc_3_9 ))
        (at-loc_2_9 )
        (box-loc_3_9 )
        (clear-loc_1_9 ))
    )


    (:action push-loc_3_9-loc_2_9
     :parameters ()
     :precondition (and (and (clear-loc_1_9 ) (at-loc_3_9 )) (box-loc_2_9 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (box-loc_2_9 ))
        (not (clear-loc_1_9 ))
        (at-loc_2_9 )
        (box-loc_1_9 )
        (clear-loc_3_9 ))
    )


    (:action push-loc_2_2-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_4_2 ) (at-loc_2_2 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_2_2 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_4_2 ))
        (at-loc_3_2 )
        (box-loc_4_2 )
        (clear-loc_2_2 ))
    )


    (:action push-loc_4_2-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_2_2 ) (at-loc_4_2 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_2_2 ))
        (at-loc_3_2 )
        (box-loc_2_2 )
        (clear-loc_4_2 ))
    )


    (:action push-loc_2_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_2_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_4_4 ))
        (at-loc_3_4 )
        (box-loc_4_4 )
        (clear-loc_2_4 ))
    )


    (:action push-loc_4_4-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_2_4 ) (at-loc_4_4 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_2_4 ))
        (at-loc_3_4 )
        (box-loc_2_4 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_2_6-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_4_6 ) (at-loc_2_6 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_4_6 ))
        (at-loc_3_6 )
        (box-loc_4_6 )
        (clear-loc_2_6 ))
    )


    (:action push-loc_4_6-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_2_6 ) (at-loc_4_6 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_2_6 ))
        (at-loc_3_6 )
        (box-loc_2_6 )
        (clear-loc_4_6 ))
    )


    (:action push-loc_2_8-loc_3_8
     :parameters ()
     :precondition (and (and (clear-loc_4_8 ) (at-loc_2_8 )) (box-loc_3_8 ))
     :effect (and
        (not (at-loc_2_8 ))
        (not (box-loc_3_8 ))
        (not (clear-loc_4_8 ))
        (at-loc_3_8 )
        (box-loc_4_8 )
        (clear-loc_2_8 ))
    )


    (:action push-loc_4_8-loc_3_8
     :parameters ()
     :precondition (and (and (clear-loc_2_8 ) (at-loc_4_8 )) (box-loc_3_8 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (box-loc_3_8 ))
        (not (clear-loc_2_8 ))
        (at-loc_3_8 )
        (box-loc_2_8 )
        (clear-loc_4_8 ))
    )


    (:action push-loc_3_2-loc_4_2
     :parameters ()
     :precondition (and (and (clear-loc_5_2 ) (at-loc_3_2 )) (box-loc_4_2 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (box-loc_4_2 ))
        (not (clear-loc_5_2 ))
        (at-loc_4_2 )
        (box-loc_5_2 )
        (clear-loc_3_2 ))
    )


    (:action push-loc_5_2-loc_4_2
     :parameters ()
     :precondition (and (and (clear-loc_3_2 ) (at-loc_5_2 )) (box-loc_4_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (box-loc_4_2 ))
        (not (clear-loc_3_2 ))
        (at-loc_4_2 )
        (box-loc_3_2 )
        (clear-loc_5_2 ))
    )


    (:action push-loc_3_8-loc_4_8
     :parameters ()
     :precondition (and (and (clear-loc_5_8 ) (at-loc_3_8 )) (box-loc_4_8 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (box-loc_4_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_4_8 )
        (box-loc_5_8 )
        (clear-loc_3_8 ))
    )


    (:action push-loc_5_8-loc_4_8
     :parameters ()
     :precondition (and (and (clear-loc_3_8 ) (at-loc_5_8 )) (box-loc_4_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (box-loc_4_8 ))
        (not (clear-loc_3_8 ))
        (at-loc_4_8 )
        (box-loc_3_8 )
        (clear-loc_5_8 ))
    )


    (:action push-loc_4_2-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_6_2 ) (at-loc_4_2 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_6_2 ))
        (at-loc_5_2 )
        (box-loc_6_2 )
        (clear-loc_4_2 ))
    )


    (:action push-loc_6_2-loc_5_2
     :parameters ()
     :precondition (and (and (clear-loc_4_2 ) (at-loc_6_2 )) (box-loc_5_2 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (box-loc_5_2 ))
        (not (clear-loc_4_2 ))
        (at-loc_5_2 )
        (box-loc_4_2 )
        (clear-loc_6_2 ))
    )


    (:action push-loc_4_8-loc_5_8
     :parameters ()
     :precondition (and (and (clear-loc_6_8 ) (at-loc_4_8 )) (box-loc_5_8 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (box-loc_5_8 ))
        (not (clear-loc_6_8 ))
        (at-loc_5_8 )
        (box-loc_6_8 )
        (clear-loc_4_8 ))
    )


    (:action push-loc_6_8-loc_5_8
     :parameters ()
     :precondition (and (and (clear-loc_4_8 ) (at-loc_6_8 )) (box-loc_5_8 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (box-loc_5_8 ))
        (not (clear-loc_4_8 ))
        (at-loc_5_8 )
        (box-loc_4_8 )
        (clear-loc_6_8 ))
    )


    (:action push-loc_5_1-loc_6_1
     :parameters ()
     :precondition (and (and (clear-loc_7_1 ) (at-loc_5_1 )) (box-loc_6_1 ))
     :effect (and
        (not (at-loc_5_1 ))
        (not (box-loc_6_1 ))
        (not (clear-loc_7_1 ))
        (at-loc_6_1 )
        (box-loc_7_1 )
        (clear-loc_5_1 ))
    )


    (:action push-loc_7_1-loc_6_1
     :parameters ()
     :precondition (and (and (clear-loc_5_1 ) (at-loc_7_1 )) (box-loc_6_1 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (box-loc_6_1 ))
        (not (clear-loc_5_1 ))
        (at-loc_6_1 )
        (box-loc_5_1 )
        (clear-loc_7_1 ))
    )


    (:action push-loc_5_2-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_7_2 ) (at-loc_5_2 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_5_2 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_7_2 ))
        (at-loc_6_2 )
        (box-loc_7_2 )
        (clear-loc_5_2 ))
    )


    (:action push-loc_7_2-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_5_2 ) (at-loc_7_2 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_7_2 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_5_2 ))
        (at-loc_6_2 )
        (box-loc_5_2 )
        (clear-loc_7_2 ))
    )


    (:action push-loc_5_8-loc_6_8
     :parameters ()
     :precondition (and (and (clear-loc_7_8 ) (at-loc_5_8 )) (box-loc_6_8 ))
     :effect (and
        (not (at-loc_5_8 ))
        (not (box-loc_6_8 ))
        (not (clear-loc_7_8 ))
        (at-loc_6_8 )
        (box-loc_7_8 )
        (clear-loc_5_8 ))
    )


    (:action push-loc_7_8-loc_6_8
     :parameters ()
     :precondition (and (and (clear-loc_5_8 ) (at-loc_7_8 )) (box-loc_6_8 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (box-loc_6_8 ))
        (not (clear-loc_5_8 ))
        (at-loc_6_8 )
        (box-loc_5_8 )
        (clear-loc_7_8 ))
    )


    (:action push-loc_5_9-loc_6_9
     :parameters ()
     :precondition (and (and (clear-loc_7_9 ) (at-loc_5_9 )) (box-loc_6_9 ))
     :effect (and
        (not (at-loc_5_9 ))
        (not (box-loc_6_9 ))
        (not (clear-loc_7_9 ))
        (at-loc_6_9 )
        (box-loc_7_9 )
        (clear-loc_5_9 ))
    )


    (:action push-loc_7_9-loc_6_9
     :parameters ()
     :precondition (and (and (clear-loc_5_9 ) (at-loc_7_9 )) (box-loc_6_9 ))
     :effect (and
        (not (at-loc_7_9 ))
        (not (box-loc_6_9 ))
        (not (clear-loc_5_9 ))
        (at-loc_6_9 )
        (box-loc_5_9 )
        (clear-loc_7_9 ))
    )


    (:action push-loc_6_5-loc_7_5
     :parameters ()
     :precondition (and (and (clear-loc_8_5 ) (at-loc_6_5 )) (box-loc_7_5 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_7_5 ))
        (not (clear-loc_8_5 ))
        (at-loc_7_5 )
        (box-loc_8_5 )
        (clear-loc_6_5 ))
    )


    (:action push-loc_8_5-loc_7_5
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_8_5 )) (box-loc_7_5 ))
     :effect (and
        (not (at-loc_8_5 ))
        (not (box-loc_7_5 ))
        (not (clear-loc_6_5 ))
        (at-loc_7_5 )
        (box-loc_6_5 )
        (clear-loc_8_5 ))
    )


    (:action push-loc_7_5-loc_8_5
     :parameters ()
     :precondition (and (and (clear-loc_9_5 ) (at-loc_7_5 )) (box-loc_8_5 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (box-loc_8_5 ))
        (not (clear-loc_9_5 ))
        (at-loc_8_5 )
        (box-loc_9_5 )
        (clear-loc_7_5 ))
    )


    (:action push-loc_9_5-loc_8_5
     :parameters ()
     :precondition (and (and (clear-loc_7_5 ) (at-loc_9_5 )) (box-loc_8_5 ))
     :effect (and
        (not (at-loc_9_5 ))
        (not (box-loc_8_5 ))
        (not (clear-loc_7_5 ))
        (at-loc_8_5 )
        (box-loc_7_5 )
        (clear-loc_9_5 ))
    )


    (:action push-loc_0_4-loc_0_5
     :parameters ()
     :precondition (and (and (clear-loc_0_6 ) (at-loc_0_4 )) (box-loc_0_5 ))
     :effect (and
        (not (at-loc_0_4 ))
        (not (box-loc_0_5 ))
        (not (clear-loc_0_6 ))
        (at-loc_0_5 )
        (box-loc_0_6 )
        (clear-loc_0_4 ))
    )


    (:action push-loc_0_6-loc_0_5
     :parameters ()
     :precondition (and (and (clear-loc_0_4 ) (at-loc_0_6 )) (box-loc_0_5 ))
     :effect (and
        (not (at-loc_0_6 ))
        (not (box-loc_0_5 ))
        (not (clear-loc_0_4 ))
        (at-loc_0_5 )
        (box-loc_0_4 )
        (clear-loc_0_6 ))
    )


    (:action push-loc_2_4-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_2_6 ) (at-loc_2_4 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_2_4 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_2_6 ))
        (at-loc_2_5 )
        (box-loc_2_6 )
        (clear-loc_2_4 ))
    )


    (:action push-loc_2_6-loc_2_5
     :parameters ()
     :precondition (and (and (clear-loc_2_4 ) (at-loc_2_6 )) (box-loc_2_5 ))
     :effect (and
        (not (at-loc_2_6 ))
        (not (box-loc_2_5 ))
        (not (clear-loc_2_4 ))
        (at-loc_2_5 )
        (box-loc_2_4 )
        (clear-loc_2_6 ))
    )


    (:action push-loc_3_1-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_3_1 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_3_1 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_2 )
        (box-loc_3_3 )
        (clear-loc_3_1 ))
    )


    (:action push-loc_3_3-loc_3_2
     :parameters ()
     :precondition (and (and (clear-loc_3_1 ) (at-loc_3_3 )) (box-loc_3_2 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_3_2 ))
        (not (clear-loc_3_1 ))
        (at-loc_3_2 )
        (box-loc_3_1 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_3_2-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_3_2 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_3_2 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_3 )
        (box-loc_3_4 )
        (clear-loc_3_2 ))
    )


    (:action push-loc_3_4-loc_3_3
     :parameters ()
     :precondition (and (and (clear-loc_3_2 ) (at-loc_3_4 )) (box-loc_3_3 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_3_3 ))
        (not (clear-loc_3_2 ))
        (at-loc_3_3 )
        (box-loc_3_2 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_3_3-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_3_3 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_3 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_4 )
        (box-loc_3_5 )
        (clear-loc_3_3 ))
    )


    (:action push-loc_3_5-loc_3_4
     :parameters ()
     :precondition (and (and (clear-loc_3_3 ) (at-loc_3_5 )) (box-loc_3_4 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_3_4 ))
        (not (clear-loc_3_3 ))
        (at-loc_3_4 )
        (box-loc_3_3 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_3_4-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_3_6 ) (at-loc_3_4 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_3_4 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_5 )
        (box-loc_3_6 )
        (clear-loc_3_4 ))
    )


    (:action push-loc_3_6-loc_3_5
     :parameters ()
     :precondition (and (and (clear-loc_3_4 ) (at-loc_3_6 )) (box-loc_3_5 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (box-loc_3_5 ))
        (not (clear-loc_3_4 ))
        (at-loc_3_5 )
        (box-loc_3_4 )
        (clear-loc_3_6 ))
    )


    (:action push-loc_3_5-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_3_7 ) (at-loc_3_5 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_3_5 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_6 )
        (box-loc_3_7 )
        (clear-loc_3_5 ))
    )


    (:action push-loc_3_7-loc_3_6
     :parameters ()
     :precondition (and (and (clear-loc_3_5 ) (at-loc_3_7 )) (box-loc_3_6 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (box-loc_3_6 ))
        (not (clear-loc_3_5 ))
        (at-loc_3_6 )
        (box-loc_3_5 )
        (clear-loc_3_7 ))
    )


    (:action push-loc_3_6-loc_3_7
     :parameters ()
     :precondition (and (and (clear-loc_3_8 ) (at-loc_3_6 )) (box-loc_3_7 ))
     :effect (and
        (not (at-loc_3_6 ))
        (not (box-loc_3_7 ))
        (not (clear-loc_3_8 ))
        (at-loc_3_7 )
        (box-loc_3_8 )
        (clear-loc_3_6 ))
    )


    (:action push-loc_3_8-loc_3_7
     :parameters ()
     :precondition (and (and (clear-loc_3_6 ) (at-loc_3_8 )) (box-loc_3_7 ))
     :effect (and
        (not (at-loc_3_8 ))
        (not (box-loc_3_7 ))
        (not (clear-loc_3_6 ))
        (at-loc_3_7 )
        (box-loc_3_6 )
        (clear-loc_3_8 ))
    )


    (:action push-loc_3_7-loc_3_8
     :parameters ()
     :precondition (and (and (clear-loc_3_9 ) (at-loc_3_7 )) (box-loc_3_8 ))
     :effect (and
        (not (at-loc_3_7 ))
        (not (box-loc_3_8 ))
        (not (clear-loc_3_9 ))
        (at-loc_3_8 )
        (box-loc_3_9 )
        (clear-loc_3_7 ))
    )


    (:action push-loc_3_9-loc_3_8
     :parameters ()
     :precondition (and (and (clear-loc_3_7 ) (at-loc_3_9 )) (box-loc_3_8 ))
     :effect (and
        (not (at-loc_3_9 ))
        (not (box-loc_3_8 ))
        (not (clear-loc_3_7 ))
        (at-loc_3_8 )
        (box-loc_3_7 )
        (clear-loc_3_9 ))
    )


    (:action push-loc_4_2-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_4_4 ) (at-loc_4_2 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_4_2 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_4_4 ))
        (at-loc_4_3 )
        (box-loc_4_4 )
        (clear-loc_4_2 ))
    )


    (:action push-loc_4_4-loc_4_3
     :parameters ()
     :precondition (and (and (clear-loc_4_2 ) (at-loc_4_4 )) (box-loc_4_3 ))
     :effect (and
        (not (at-loc_4_4 ))
        (not (box-loc_4_3 ))
        (not (clear-loc_4_2 ))
        (at-loc_4_3 )
        (box-loc_4_2 )
        (clear-loc_4_4 ))
    )


    (:action push-loc_4_6-loc_4_7
     :parameters ()
     :precondition (and (and (clear-loc_4_8 ) (at-loc_4_6 )) (box-loc_4_7 ))
     :effect (and
        (not (at-loc_4_6 ))
        (not (box-loc_4_7 ))
        (not (clear-loc_4_8 ))
        (at-loc_4_7 )
        (box-loc_4_8 )
        (clear-loc_4_6 ))
    )


    (:action push-loc_4_8-loc_4_7
     :parameters ()
     :precondition (and (and (clear-loc_4_6 ) (at-loc_4_8 )) (box-loc_4_7 ))
     :effect (and
        (not (at-loc_4_8 ))
        (not (box-loc_4_7 ))
        (not (clear-loc_4_6 ))
        (at-loc_4_7 )
        (box-loc_4_6 )
        (clear-loc_4_8 ))
    )


    (:action push-loc_6_1-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_6_1 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_6_1 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_2 )
        (box-loc_6_3 )
        (clear-loc_6_1 ))
    )


    (:action push-loc_6_3-loc_6_2
     :parameters ()
     :precondition (and (and (clear-loc_6_1 ) (at-loc_6_3 )) (box-loc_6_2 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_6_2 ))
        (not (clear-loc_6_1 ))
        (at-loc_6_2 )
        (box-loc_6_1 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_6_2-loc_6_3
     :parameters ()
     :precondition (and (and (clear-loc_6_4 ) (at-loc_6_2 )) (box-loc_6_3 ))
     :effect (and
        (not (at-loc_6_2 ))
        (not (box-loc_6_3 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_3 )
        (box-loc_6_4 )
        (clear-loc_6_2 ))
    )


    (:action push-loc_6_4-loc_6_3
     :parameters ()
     :precondition (and (and (clear-loc_6_2 ) (at-loc_6_4 )) (box-loc_6_3 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (box-loc_6_3 ))
        (not (clear-loc_6_2 ))
        (at-loc_6_3 )
        (box-loc_6_2 )
        (clear-loc_6_4 ))
    )


    (:action push-loc_6_3-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_6_3 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_3 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_4 )
        (box-loc_6_5 )
        (clear-loc_6_3 ))
    )


    (:action push-loc_6_5-loc_6_4
     :parameters ()
     :precondition (and (and (clear-loc_6_3 ) (at-loc_6_5 )) (box-loc_6_4 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_6_4 ))
        (not (clear-loc_6_3 ))
        (at-loc_6_4 )
        (box-loc_6_3 )
        (clear-loc_6_5 ))
    )


    (:action push-loc_6_4-loc_6_5
     :parameters ()
     :precondition (and (and (clear-loc_6_6 ) (at-loc_6_4 )) (box-loc_6_5 ))
     :effect (and
        (not (at-loc_6_4 ))
        (not (box-loc_6_5 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_5 )
        (box-loc_6_6 )
        (clear-loc_6_4 ))
    )


    (:action push-loc_6_6-loc_6_5
     :parameters ()
     :precondition (and (and (clear-loc_6_4 ) (at-loc_6_6 )) (box-loc_6_5 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (box-loc_6_5 ))
        (not (clear-loc_6_4 ))
        (at-loc_6_5 )
        (box-loc_6_4 )
        (clear-loc_6_6 ))
    )


    (:action push-loc_6_5-loc_6_6
     :parameters ()
     :precondition (and (and (clear-loc_6_7 ) (at-loc_6_5 )) (box-loc_6_6 ))
     :effect (and
        (not (at-loc_6_5 ))
        (not (box-loc_6_6 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_6 )
        (box-loc_6_7 )
        (clear-loc_6_5 ))
    )


    (:action push-loc_6_7-loc_6_6
     :parameters ()
     :precondition (and (and (clear-loc_6_5 ) (at-loc_6_7 )) (box-loc_6_6 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (box-loc_6_6 ))
        (not (clear-loc_6_5 ))
        (at-loc_6_6 )
        (box-loc_6_5 )
        (clear-loc_6_7 ))
    )


    (:action push-loc_6_6-loc_6_7
     :parameters ()
     :precondition (and (and (clear-loc_6_8 ) (at-loc_6_6 )) (box-loc_6_7 ))
     :effect (and
        (not (at-loc_6_6 ))
        (not (box-loc_6_7 ))
        (not (clear-loc_6_8 ))
        (at-loc_6_7 )
        (box-loc_6_8 )
        (clear-loc_6_6 ))
    )


    (:action push-loc_6_8-loc_6_7
     :parameters ()
     :precondition (and (and (clear-loc_6_6 ) (at-loc_6_8 )) (box-loc_6_7 ))
     :effect (and
        (not (at-loc_6_8 ))
        (not (box-loc_6_7 ))
        (not (clear-loc_6_6 ))
        (at-loc_6_7 )
        (box-loc_6_6 )
        (clear-loc_6_8 ))
    )


    (:action push-loc_6_7-loc_6_8
     :parameters ()
     :precondition (and (and (clear-loc_6_9 ) (at-loc_6_7 )) (box-loc_6_8 ))
     :effect (and
        (not (at-loc_6_7 ))
        (not (box-loc_6_8 ))
        (not (clear-loc_6_9 ))
        (at-loc_6_8 )
        (box-loc_6_9 )
        (clear-loc_6_7 ))
    )


    (:action push-loc_6_9-loc_6_8
     :parameters ()
     :precondition (and (and (clear-loc_6_7 ) (at-loc_6_9 )) (box-loc_6_8 ))
     :effect (and
        (not (at-loc_6_9 ))
        (not (box-loc_6_8 ))
        (not (clear-loc_6_7 ))
        (at-loc_6_8 )
        (box-loc_6_7 )
        (clear-loc_6_9 ))
    )


    (:action push-loc_7_1-loc_7_2
     :parameters ()
     :precondition (and (and (clear-loc_7_3 ) (at-loc_7_1 )) (box-loc_7_2 ))
     :effect (and
        (not (at-loc_7_1 ))
        (not (box-loc_7_2 ))
        (not (clear-loc_7_3 ))
        (at-loc_7_2 )
        (box-loc_7_3 )
        (clear-loc_7_1 ))
    )


    (:action push-loc_7_3-loc_7_2
     :parameters ()
     :precondition (and (and (clear-loc_7_1 ) (at-loc_7_3 )) (box-loc_7_2 ))
     :effect (and
        (not (at-loc_7_3 ))
        (not (box-loc_7_2 ))
        (not (clear-loc_7_1 ))
        (at-loc_7_2 )
        (box-loc_7_1 )
        (clear-loc_7_3 ))
    )


    (:action push-loc_7_2-loc_7_3
     :parameters ()
     :precondition (and (and (clear-loc_7_4 ) (at-loc_7_2 )) (box-loc_7_3 ))
     :effect (and
        (not (at-loc_7_2 ))
        (not (box-loc_7_3 ))
        (not (clear-loc_7_4 ))
        (at-loc_7_3 )
        (box-loc_7_4 )
        (clear-loc_7_2 ))
    )


    (:action push-loc_7_4-loc_7_3
     :parameters ()
     :precondition (and (and (clear-loc_7_2 ) (at-loc_7_4 )) (box-loc_7_3 ))
     :effect (and
        (not (at-loc_7_4 ))
        (not (box-loc_7_3 ))
        (not (clear-loc_7_2 ))
        (at-loc_7_3 )
        (box-loc_7_2 )
        (clear-loc_7_4 ))
    )


    (:action push-loc_7_3-loc_7_4
     :parameters ()
     :precondition (and (and (clear-loc_7_5 ) (at-loc_7_3 )) (box-loc_7_4 ))
     :effect (and
        (not (at-loc_7_3 ))
        (not (box-loc_7_4 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_4 )
        (box-loc_7_5 )
        (clear-loc_7_3 ))
    )


    (:action push-loc_7_5-loc_7_4
     :parameters ()
     :precondition (and (and (clear-loc_7_3 ) (at-loc_7_5 )) (box-loc_7_4 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (box-loc_7_4 ))
        (not (clear-loc_7_3 ))
        (at-loc_7_4 )
        (box-loc_7_3 )
        (clear-loc_7_5 ))
    )


    (:action push-loc_7_4-loc_7_5
     :parameters ()
     :precondition (and (and (clear-loc_7_6 ) (at-loc_7_4 )) (box-loc_7_5 ))
     :effect (and
        (not (at-loc_7_4 ))
        (not (box-loc_7_5 ))
        (not (clear-loc_7_6 ))
        (at-loc_7_5 )
        (box-loc_7_6 )
        (clear-loc_7_4 ))
    )


    (:action push-loc_7_6-loc_7_5
     :parameters ()
     :precondition (and (and (clear-loc_7_4 ) (at-loc_7_6 )) (box-loc_7_5 ))
     :effect (and
        (not (at-loc_7_6 ))
        (not (box-loc_7_5 ))
        (not (clear-loc_7_4 ))
        (at-loc_7_5 )
        (box-loc_7_4 )
        (clear-loc_7_6 ))
    )


    (:action push-loc_7_5-loc_7_6
     :parameters ()
     :precondition (and (and (clear-loc_7_7 ) (at-loc_7_5 )) (box-loc_7_6 ))
     :effect (and
        (not (at-loc_7_5 ))
        (not (box-loc_7_6 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_6 )
        (box-loc_7_7 )
        (clear-loc_7_5 ))
    )


    (:action push-loc_7_7-loc_7_6
     :parameters ()
     :precondition (and (and (clear-loc_7_5 ) (at-loc_7_7 )) (box-loc_7_6 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (box-loc_7_6 ))
        (not (clear-loc_7_5 ))
        (at-loc_7_6 )
        (box-loc_7_5 )
        (clear-loc_7_7 ))
    )


    (:action push-loc_7_6-loc_7_7
     :parameters ()
     :precondition (and (and (clear-loc_7_8 ) (at-loc_7_6 )) (box-loc_7_7 ))
     :effect (and
        (not (at-loc_7_6 ))
        (not (box-loc_7_7 ))
        (not (clear-loc_7_8 ))
        (at-loc_7_7 )
        (box-loc_7_8 )
        (clear-loc_7_6 ))
    )


    (:action push-loc_7_8-loc_7_7
     :parameters ()
     :precondition (and (and (clear-loc_7_6 ) (at-loc_7_8 )) (box-loc_7_7 ))
     :effect (and
        (not (at-loc_7_8 ))
        (not (box-loc_7_7 ))
        (not (clear-loc_7_6 ))
        (at-loc_7_7 )
        (box-loc_7_6 )
        (clear-loc_7_8 ))
    )


    (:action push-loc_7_7-loc_7_8
     :parameters ()
     :precondition (and (and (clear-loc_7_9 ) (at-loc_7_7 )) (box-loc_7_8 ))
     :effect (and
        (not (at-loc_7_7 ))
        (not (box-loc_7_8 ))
        (not (clear-loc_7_9 ))
        (at-loc_7_8 )
        (box-loc_7_9 )
        (clear-loc_7_7 ))
    )


    (:action push-loc_7_9-loc_7_8
     :parameters ()
     :precondition (and (and (clear-loc_7_7 ) (at-loc_7_9 )) (box-loc_7_8 ))
     :effect (and
        (not (at-loc_7_9 ))
        (not (box-loc_7_8 ))
        (not (clear-loc_7_7 ))
        (at-loc_7_8 )
        (box-loc_7_7 )
        (clear-loc_7_9 ))
    )


    (:action push-loc_9_0-loc_9_1
     :parameters ()
     :precondition (and (and (clear-loc_9_2 ) (at-loc_9_0 )) (box-loc_9_1 ))
     :effect (and
        (not (at-loc_9_0 ))
        (not (box-loc_9_1 ))
        (not (clear-loc_9_2 ))
        (at-loc_9_1 )
        (box-loc_9_2 )
        (clear-loc_9_0 ))
    )


    (:action push-loc_9_2-loc_9_1
     :parameters ()
     :precondition (and (and (clear-loc_9_0 ) (at-loc_9_2 )) (box-loc_9_1 ))
     :effect (and
        (not (at-loc_9_2 ))
        (not (box-loc_9_1 ))
        (not (clear-loc_9_0 ))
        (at-loc_9_1 )
        (box-loc_9_0 )
        (clear-loc_9_2 ))
    )


    (:action push-loc_9_1-loc_9_2
     :parameters ()
     :precondition (and (and (clear-loc_9_3 ) (at-loc_9_1 )) (box-loc_9_2 ))
     :effect (and
        (not (at-loc_9_1 ))
        (not (box-loc_9_2 ))
        (not (clear-loc_9_3 ))
        (at-loc_9_2 )
        (box-loc_9_3 )
        (clear-loc_9_1 ))
    )


    (:action push-loc_9_3-loc_9_2
     :parameters ()
     :precondition (and (and (clear-loc_9_1 ) (at-loc_9_3 )) (box-loc_9_2 ))
     :effect (and
        (not (at-loc_9_3 ))
        (not (box-loc_9_2 ))
        (not (clear-loc_9_1 ))
        (at-loc_9_2 )
        (box-loc_9_1 )
        (clear-loc_9_3 ))
    )


    (:action push-loc_9_7-loc_9_8
     :parameters ()
     :precondition (and (and (clear-loc_9_9 ) (at-loc_9_7 )) (box-loc_9_8 ))
     :effect (and
        (not (at-loc_9_7 ))
        (not (box-loc_9_8 ))
        (not (clear-loc_9_9 ))
        (at-loc_9_8 )
        (box-loc_9_9 )
        (clear-loc_9_7 ))
    )


    (:action push-loc_9_9-loc_9_8
     :parameters ()
     :precondition (and (and (clear-loc_9_7 ) (at-loc_9_9 )) (box-loc_9_8 ))
     :effect (and
        (not (at-loc_9_9 ))
        (not (box-loc_9_8 ))
        (not (clear-loc_9_7 ))
        (at-loc_9_8 )
        (box-loc_9_7 )
        (clear-loc_9_9 ))
    )


    (:action push-loc_9_8-loc_9_9
     :parameters ()
     :precondition (and (and (clear-loc_9_10 ) (at-loc_9_8 )) (box-loc_9_9 ))
     :effect (and
        (not (at-loc_9_8 ))
        (not (box-loc_9_9 ))
        (not (clear-loc_9_10 ))
        (at-loc_9_9 )
        (box-loc_9_10 )
        (clear-loc_9_8 ))
    )


    (:action push-loc_9_10-loc_9_9
     :parameters ()
     :precondition (and (and (clear-loc_9_8 ) (at-loc_9_10 )) (box-loc_9_9 ))
     :effect (and
        (not (at-loc_9_10 ))
        (not (box-loc_9_9 ))
        (not (clear-loc_9_8 ))
        (at-loc_9_9 )
        (box-loc_9_8 )
        (clear-loc_9_10 ))
    )


    (:action push-loc_10_0-loc_10_1
     :parameters ()
     :precondition (and (and (clear-loc_10_2 ) (at-loc_10_0 )) (box-loc_10_1 ))
     :effect (and
        (not (at-loc_10_0 ))
        (not (box-loc_10_1 ))
        (not (clear-loc_10_2 ))
        (at-loc_10_1 )
        (box-loc_10_2 )
        (clear-loc_10_0 ))
    )


    (:action push-loc_10_2-loc_10_1
     :parameters ()
     :precondition (and (and (clear-loc_10_0 ) (at-loc_10_2 )) (box-loc_10_1 ))
     :effect (and
        (not (at-loc_10_2 ))
        (not (box-loc_10_1 ))
        (not (clear-loc_10_0 ))
        (at-loc_10_1 )
        (box-loc_10_0 )
        (clear-loc_10_2 ))
    )


    (:action push-loc_10_1-loc_10_2
     :parameters ()
     :precondition (and (and (clear-loc_10_3 ) (at-loc_10_1 )) (box-loc_10_2 ))
     :effect (and
        (not (at-loc_10_1 ))
        (not (box-loc_10_2 ))
        (not (clear-loc_10_3 ))
        (at-loc_10_2 )
        (box-loc_10_3 )
        (clear-loc_10_1 ))
    )


    (:action push-loc_10_3-loc_10_2
     :parameters ()
     :precondition (and (and (clear-loc_10_1 ) (at-loc_10_3 )) (box-loc_10_2 ))
     :effect (and
        (not (at-loc_10_3 ))
        (not (box-loc_10_2 ))
        (not (clear-loc_10_1 ))
        (at-loc_10_2 )
        (box-loc_10_1 )
        (clear-loc_10_3 ))
    )


    (:action push-loc_10_7-loc_10_8
     :parameters ()
     :precondition (and (and (clear-loc_10_9 ) (at-loc_10_7 )) (box-loc_10_8 ))
     :effect (and
        (not (at-loc_10_7 ))
        (not (box-loc_10_8 ))
        (not (clear-loc_10_9 ))
        (at-loc_10_8 )
        (box-loc_10_9 )
        (clear-loc_10_7 ))
    )


    (:action push-loc_10_9-loc_10_8
     :parameters ()
     :precondition (and (and (clear-loc_10_7 ) (at-loc_10_9 )) (box-loc_10_8 ))
     :effect (and
        (not (at-loc_10_9 ))
        (not (box-loc_10_8 ))
        (not (clear-loc_10_7 ))
        (at-loc_10_8 )
        (box-loc_10_7 )
        (clear-loc_10_9 ))
    )


    (:action push-loc_10_8-loc_10_9
     :parameters ()
     :precondition (and (and (clear-loc_10_10 ) (at-loc_10_8 )) (box-loc_10_9 ))
     :effect (and
        (not (at-loc_10_8 ))
        (not (box-loc_10_9 ))
        (not (clear-loc_10_10 ))
        (at-loc_10_9 )
        (box-loc_10_10 )
        (clear-loc_10_8 ))
    )


    (:action push-loc_10_10-loc_10_9
     :parameters ()
     :precondition (and (and (clear-loc_10_8 ) (at-loc_10_10 )) (box-loc_10_9 ))
     :effect (and
        (not (at-loc_10_10 ))
        (not (box-loc_10_9 ))
        (not (clear-loc_10_8 ))
        (at-loc_10_9 )
        (box-loc_10_8 )
        (clear-loc_10_10 ))
    )

)