
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance_30007)
    (:domain Sokoban)

    (:objects
        
    )

    (:init
        (clear-loc_0_4 )
        (clear-loc_0_5 )
        (clear-loc_0_6 )
        (clear-loc_1_1 )
        (clear-loc_1_2 )
        (clear-loc_1_8 )
        (clear-loc_1_9 )
        (clear-loc_2_1 )
        (clear-loc_2_2 )
        (clear-loc_2_4 )
        (clear-loc_2_5 )
        (clear-loc_2_6 )
        (clear-loc_2_8 )
        (clear-loc_2_9 )
        (clear-loc_3_1 )
        (clear-loc_3_2 )
        (clear-loc_3_3 )
        (clear-loc_3_4 )
        (clear-loc_3_5 )
        (clear-loc_3_6 )
        (clear-loc_3_7 )
        (clear-loc_3_8 )
        (clear-loc_3_9 )
        (clear-loc_4_2 )
        (clear-loc_4_3 )
        (clear-loc_4_4 )
        (clear-loc_4_6 )
        (clear-loc_4_7 )
        (clear-loc_4_8 )
        (clear-loc_5_1 )
        (clear-loc_5_2 )
        (clear-loc_5_8 )
        (clear-loc_5_9 )
        (clear-loc_6_1 )
        (clear-loc_6_2 )
        (clear-loc_6_3 )
        (clear-loc_6_4 )
        (box-loc_6_5 )
        (clear-loc_6_6 )
        (clear-loc_6_7 )
        (clear-loc_6_8 )
        (clear-loc_6_9 )
        (clear-loc_7_1 )
        (clear-loc_7_2 )
        (clear-loc_7_3 )
        (clear-loc_7_4 )
        (clear-loc_7_5 )
        (clear-loc_7_6 )
        (clear-loc_7_7 )
        (clear-loc_7_8 )
        (clear-loc_7_9 )
        (clear-loc_8_5 )
        (clear-loc_9_0 )
        (clear-loc_9_1 )
        (clear-loc_9_2 )
        (clear-loc_9_3 )
        (at-loc_9_5 )
        (clear-loc_9_7 )
        (clear-loc_9_8 )
        (clear-loc_9_9 )
        (clear-loc_9_10 )
        (clear-loc_10_0 )
        (clear-loc_10_1 )
        (clear-loc_10_2 )
        (clear-loc_10_3 )
        (clear-loc_10_7 )
        (clear-loc_10_8 )
        (clear-loc_10_9 )
        (clear-loc_10_10 )
    )

    (:goal
        (box-loc_4_3 )
    )

    
    
    
)

