
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance_30013)
    (:domain Sokoban)

    (:objects
        
    )

    (:init
        (clear-loc_0_0 )
        (clear-loc_0_6 )
        (clear-loc_0_7 )
        (clear-loc_0_8 )
        (clear-loc_1_0 )
        (clear-loc_1_2 )
        (clear-loc_1_3 )
        (clear-loc_1_4 )
        (clear-loc_1_6 )
        (clear-loc_1_7 )
        (clear-loc_1_8 )
        (clear-loc_2_0 )
        (clear-loc_2_3 )
        (clear-loc_2_4 )
        (clear-loc_2_7 )
        (clear-loc_2_8 )
        (clear-loc_3_2 )
        (clear-loc_3_3 )
        (clear-loc_3_4 )
        (clear-loc_3_5 )
        (clear-loc_4_1 )
        (clear-loc_4_2 )
        (clear-loc_4_3 )
        (box-loc_4_4 )
        (clear-loc_4_5 )
        (clear-loc_4_6 )
        (at-loc_4_7 )
        (clear-loc_5_3 )
        (clear-loc_5_5 )
        (clear-loc_6_0 )
        (clear-loc_6_1 )
        (clear-loc_6_3 )
        (clear-loc_6_4 )
        (clear-loc_6_5 )
        (clear-loc_6_7 )
        (clear-loc_6_8 )
        (clear-loc_7_0 )
        (clear-loc_7_1 )
        (clear-loc_7_7 )
        (clear-loc_7_8 )
    )

    (:goal
        (box-loc_4_1 )
    )

    
    
    
)

