
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; Instance file automatically generated by the Tarski FSTRIPS writer
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (problem instance_30003)
    (:domain Sokoban)

    (:objects
        
    )

    (:init
        (clear-loc_0_8 )
        (clear-loc_0_9 )
        (clear-loc_0_10 )
        (clear-loc_1_1 )
        (clear-loc_1_2 )
        (clear-loc_1_4 )
        (clear-loc_1_5 )
        (clear-loc_1_6 )
        (clear-loc_1_8 )
        (clear-loc_1_9 )
        (clear-loc_1_10 )
        (clear-loc_2_1 )
        (clear-loc_2_2 )
        (clear-loc_2_3 )
        (clear-loc_2_4 )
        (clear-loc_2_6 )
        (clear-loc_2_10 )
        (clear-loc_3_2 )
        (clear-loc_3_3 )
        (clear-loc_3_4 )
        (box-loc_3_5 )
        (clear-loc_3_6 )
        (clear-loc_3_7 )
        (clear-loc_3_8 )
        (clear-loc_4_0 )
        (clear-loc_4_3 )
        (clear-loc_4_4 )
        (clear-loc_4_5 )
        (clear-loc_4_6 )
        (clear-loc_4_7 )
        (clear-loc_4_8 )
        (clear-loc_4_9 )
        (clear-loc_5_0 )
        (clear-loc_5_1 )
        (clear-loc_5_5 )
        (clear-loc_5_8 )
        (clear-loc_5_9 )
        (clear-loc_6_0 )
        (clear-loc_6_1 )
        (clear-loc_6_2 )
        (clear-loc_6_3 )
        (at-loc_6_5 )
        (clear-loc_7_0 )
        (clear-loc_7_1 )
        (clear-loc_7_2 )
        (clear-loc_7_3 )
        (clear-loc_7_7 )
        (clear-loc_7_8 )
        (clear-loc_7_9 )
        (clear-loc_7_10 )
    )

    (:goal
        (box-loc_4_9 )
    )

    
    
    
)

